import { useEffect, useState } from "react";
import { RefreshButton } from "../components/RefreshButton";

type Group = { id: string; name: string };
type Instance = { name: string; instanceId: string; state: string; privateIp: string; publicIp: string; os: string; description: string; securityGroups: Group[] };
type Response = { data: { items: Instance[]; pagination: { page: number; total: number; totalPages: number }; source: { exists: boolean }; metadata: { region?: string } } };
const searchFields = [["all", "전체"], ["name", "Name"], ["instanceId", "Instance ID"], ["privateIp", "Private IP"], ["publicIp", "Public IP"], ["description", "Description"], ["securityGroups", "Security Group"]];

export function AwsAssetPage() {
  const [items, setItems] = useState<Instance[]>([]), [query, setQuery] = useState(""), [field, setField] = useState("all"), [page, setPage] = useState(1), [total, setTotal] = useState(0), [totalPages, setTotalPages] = useState(1), [region, setRegion] = useState("-"), [sourceExists, setSourceExists] = useState(true), [loading, setLoading] = useState(true), [error, setError] = useState(""), [reloadKey, setReloadKey] = useState(0), [detail, setDetail] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { const controller = new AbortController(), timer = window.setTimeout(() => { setLoading(true); setError(""); const params = new URLSearchParams({ query, field, page: String(page), pageSize: "50" }); fetch(`/api/aws/instances?${params}`, { signal: controller.signal }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); return payload as Response; }).then(payload => { setItems(payload.data.items); setTotal(payload.data.pagination.total); setTotalPages(payload.data.pagination.totalPages); setRegion(payload.data.metadata.region || "-"); setSourceExists(payload.data.source.exists); }).catch(reason => { if ((reason as Error).name !== "AbortError") setError(String(reason)); }).finally(() => setLoading(false)); }, 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query, field, page, reloadKey]);
  const openDetail = async (instance: Instance) => { try { const response = await fetch(`/api/aws/instances/${encodeURIComponent(instance.instanceId)}`), payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); setDetail(payload.data); } catch (reason) { setError(String(reason)); } };
  return <><header className="topbar"><div><p className="breadcrumb">Asset / AWS</p><h1>AWS</h1></div><RefreshButton target="aws" onComplete={() => setReloadKey(key => key + 1)} /></header>
    <section className="summary-grid"><article><span>EC2 Instances</span><strong>{total.toLocaleString()}</strong><small>검색 조건에 일치하는 인스턴스</small></article><article><span>Region</span><strong>{region}</strong><small>cache/aws.json</small></article><article><span>데이터 소스</span><strong className={sourceExists ? "good" : "warn"}>{sourceExists ? "정상" : "없음"}</strong><small>AWS Raw Cache</small></article></section>
    <section className="panel"><div className="panel-head"><div><h2>EC2 Instance 목록</h2><p>Name, ID, IP, Description, Security Group 기준으로 검색할 수 있습니다.</p></div><div className="search-box"><select value={field} onChange={event => { setField(event.target.value); setPage(1); }}>{searchFields.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><input value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="검색어 입력..." /></div></div>
      {error && <div className="error-banner">AWS 조회 오류: {error}</div>}{!sourceExists && !error && <div className="empty-banner">AWS Raw Cache가 없습니다. AWS Credential 설정 후 새로고침을 실행해주세요.</div>}
      <div className="table-wrap"><table><thead><tr><th>Name</th><th>Instance ID</th><th>State</th><th>Private IP</th><th>Public IP</th><th>OS</th><th>Description</th><th>Security Groups</th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="state-cell">데이터를 불러오는 중입니다...</td></tr> : !items.length ? <tr><td colSpan={8} className="state-cell">표시할 AWS Instance가 없습니다.</td></tr> : items.map(item => <tr key={item.instanceId} onDoubleClick={() => openDetail(item)}><td className="hostname">{item.name}</td><td>{item.instanceId}</td><td><span className="status-pill">{item.state}</span></td><td>{item.privateIp}</td><td>{item.publicIp}</td><td>{item.os}</td><td>{item.description}</td><td><div className="integration-tags">{item.securityGroups.slice(0, 2).map(group => <i key={group.id}>{group.name}</i>)}{item.securityGroups.length > 2 && <i>+{item.securityGroups.length - 2}</i>}</div></td></tr>)}</tbody></table></div>
      <footer className="pagination"><span>총 {total.toLocaleString()}개</span><div><button disabled={page <= 1} onClick={() => setPage(page - 1)}>이전</button><b>{page} / {totalPages}</b><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>다음</button></div></footer></section>
    {detail && <div className="modal-backdrop" onMouseDown={() => setDetail(null)}><section className="detail-modal" onMouseDown={event => event.stopPropagation()}><header><div><span>AWS Instance Raw Detail</span><h2>{String((detail.instance as Record<string, unknown>)?.InstanceId || "AWS Instance")}</h2></div><button onClick={() => setDetail(null)}>×</button></header><pre>{JSON.stringify(detail, null, 2)}</pre></section></div>}
  </>;
}
