import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";

type Row={name:string;groupId:string;vpcId:string;inbound:number;outbound:number;instances:number};
type Rule={ruleId:string;protocol:string;port:string;target:string;description:string;referencedGroupId:string;referencedGroupName:string};
type Instance={name:string;instanceId:string;state:string;privateIp:string;publicIp:string;eniIds:string[]};
type Detail={group:{GroupName?:string;GroupId?:string;Description?:string;VpcId?:string};inbound:Rule[];outbound:Rule[];instances:Instance[];summary:{inbound:number;outbound:number;instances:number}};

export function AwsSecurityGroupPage(){
 const navigate=useNavigate(),[params,setParams]=useSearchParams();
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[summary,setSummary]=useState({total:0,attached:0,notAttached:0,rules:0}),[detail,setDetail]=useState<Detail|null>(null),[tab,setTab]=useState<"inbound"|"outbound"|"instances">("inbound"),[error,setError]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>{const search=new URLSearchParams({query,page:String(page),pageSize:"50"});fetch(`/api/aws/security-groups?${search}`).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||`HTTP ${r.status}`);return p.data}).then(data=>{setRows(data.items);setPages(data.pagination.totalPages);setTotal(data.pagination.total);setSummary(data.summary)}).catch(e=>setError(String(e)))},250);return()=>clearTimeout(timer)},[query,page]);
 const open=async(id:string)=>{const r=await fetch(`/api/aws/security-groups/${encodeURIComponent(id)}`),p=await r.json();if(!r.ok){setError(p?.error?.message||`HTTP ${r.status}`);return}setDetail(p.data);setTab("inbound");setParams({groupId:id})};
 useEffect(()=>{const id=params.get("groupId");if(id)void open(id)},[]);
 const close=()=>{setDetail(null);setParams({})}; const rules=tab==="inbound"?detail?.inbound:detail?.outbound;
 return <><header className="topbar"><div><p className="breadcrumb">Asset / AWS SG</p><h1>AWS SG</h1></div></header>
 <section className="summary-grid"><article><span>전체 SG</span><strong>{summary.total.toLocaleString()}</strong></article><article><span>EC2 연결 SG</span><strong>{summary.attached.toLocaleString()}</strong></article><article><span>EC2 연결 없음</span><strong>{summary.notAttached.toLocaleString()}</strong></article><article><span>전체 SG 규칙</span><strong>{summary.rules.toLocaleString()}</strong></article></section>
 <section className="panel"><div className="panel-head"><div><h2>Security Group 목록</h2><p>SG 식별자와 실제 EC2 연결 관계를 기준으로 조회합니다.</p></div><div className="search-box"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="SG, VPC, 서버명, Instance ID, IP 검색..."/></div></div>{error&&<div className="error-banner">AWS SG 조회 오류: {error}</div>}
 <div className="table-wrap"><table><thead><tr><th>SG Name</th><th>SG ID</th><th>VPC</th><th>Inbound 규칙 수</th><th>Outbound 규칙 수</th><th>적용 EC2 수</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.groupId} onDoubleClick={()=>open(row.groupId)}><td className="hostname">{row.name}</td><td>{row.groupId}</td><td>{row.vpcId}</td><td>{row.inbound}</td><td>{row.outbound}</td><td>{row.instances}</td></tr>):<tr><td colSpan={6} className="state-cell">표시할 Security Group이 없습니다.</td></tr>}</tbody></table></div><footer className="pagination"><span>검색 결과 {total.toLocaleString()}개</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>이전</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(page+1)}>다음</button></div></footer></section>
 {detail&&<div className="modal-backdrop" onMouseDown={close}><section className="detail-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>{detail.group.GroupName||"-"}</span><h2>{detail.group.GroupId}</h2></div><button onClick={close}>×</button></header><div className="firewall-detail-grid"><div><span>Description</span><b>{detail.group.Description||"-"}</b></div><div><span>VPC ID</span><b>{detail.group.VpcId||"-"}</b></div><div><span>Inbound</span><b>{detail.summary.inbound}</b></div><div><span>Outbound</span><b>{detail.summary.outbound}</b></div><div><span>적용 EC2</span><b>{detail.summary.instances}</b></div></div><div className="source-filters exception-tabs"><button className={tab==="inbound"?"active":""} onClick={()=>setTab("inbound")}>Inbound</button><button className={tab==="outbound"?"active":""} onClick={()=>setTab("outbound")}>Outbound</button><button className={tab==="instances"?"active":""} onClick={()=>setTab("instances")}>적용 서버</button></div>
 {tab!=="instances"?<div className="table-wrap"><table><thead><tr><th>Rule ID</th><th>Protocol</th><th>Port / Type</th><th>{tab==="inbound"?"Source":"Destination"}</th><th>Description</th></tr></thead><tbody>{rules?.length?rules.map(rule=><tr key={rule.ruleId}><td>{rule.ruleId}</td><td>{rule.protocol}</td><td>{rule.port}</td><td>{rule.referencedGroupId!=="-"&&rule.referencedGroupName!=="-"?<button className="sort-button" onClick={()=>open(rule.referencedGroupId)}>{rule.target}</button>:rule.target}</td><td>{rule.description}</td></tr>):<tr><td colSpan={5} className="state-cell">규칙이 없습니다.</td></tr>}</tbody></table></div>:<div className="table-wrap"><table><thead><tr><th>EC2 Name</th><th>Instance ID</th><th>State</th><th>Private IP</th><th>Public IP</th><th>ENI ID</th></tr></thead><tbody>{detail.instances.length?detail.instances.map(item=><tr key={item.instanceId}><td><button className="sort-button" onClick={()=>navigate(`/assets/aws?instanceId=${encodeURIComponent(item.instanceId)}`)}>{item.name}</button></td><td>{item.instanceId}</td><td>{item.state}</td><td>{item.privateIp}</td><td>{item.publicIp}</td><td>{item.eniIds.join(", ")||"-"}</td></tr>):<tr><td colSpan={6} className="state-cell">연결된 EC2가 없습니다.</td></tr>}</tbody></table></div>}</section></div>}</>;
}
