import {useEffect,useState} from "react";
type Status={sources:Record<string,{exists:boolean;files:number;bytes:number;latest:number|null}>;indexes:Record<string,{exists:boolean;bytes:number}>;logs:string};type Scheduler={enabled:boolean;interval:number;targets:string[];lastRun:string|null;lastResult:string};
const themeLabels:Record<string,string>={Primary_Blue:"메인 강조색",Primary_Blue_Dark:"강조 어두운 색",UI_Background:"앱 배경",UI_Surface:"카드 배경",Card_Border:"카드 테두리",Card_Title_Text:"카드 제목",Table_Header_Background:"테이블 헤더 배경",Table_Header_Text:"테이블 헤더 글씨",Table_Selection_Background:"선택 행 배경",Table_Selection_Text:"선택 행 글씨",Status_Success_Text:"성공",Status_Fail_Text:"실패",Threat_trend_Detection:"Detection 그래프",Threat_trend_Detection_XDR:"Email XDR 그래프",Threat_trend_Email:"Inbound 그래프",Threat_trend_Outbound_Mail:"Outbound 그래프",Threat_trend_File:"File 그래프"};
export function ConfigPage(){
 const today=new Date().toISOString().slice(0,10),week=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const [status,setStatus]=useState<Status|null>(null),[start,setStart]=useState(week),[end,setEnd]=useState(today),[message,setMessage]=useState(""),[running,setRunning]=useState(false),[scheduler,setScheduler]=useState<Scheduler>({enabled:false,interval:10,targets:[],lastRun:null,lastResult:"-"}),[theme,setTheme]=useState<Record<string,string>>({});
 const load=()=>Promise.all([fetch("/api/config/status").then(r=>r.json()),fetch("/api/config/scheduler").then(r=>r.json()),fetch("/api/config/theme").then(r=>r.json())]).then(([a,b,c])=>{setStatus(a.data);setScheduler(b.data);setTheme(c.data)});useEffect(()=>{load()},[]);
 const job=async(url:string,body:unknown)=>{setRunning(true);try{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message);for(;;){await new Promise(x=>setTimeout(x,800));const j=await fetch(`/api/jobs/${p.data.id}`).then(x=>x.json());setMessage(j.data.message);if(j.data.status==="completed"){await load();setRunning(false);return j.data.result}if(j.data.status==="failed")throw new Error(j.data.error?.message)}}finally{setRunning(false)}};
 const refresh=(target:string)=>job(`/api/jobs/refresh/${target}`,["detections","inbound"].includes(target)?{start,end}:{}).catch(e=>setMessage(String(e)));
 const saveScheduler=async()=>{await fetch("/api/config/scheduler",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(scheduler)});setMessage("자동 새로고침 설정 저장 완료");load()};
 const saveTheme=async()=>{const r=await fetch("/api/config/theme",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(theme)});if(r.ok){setMessage("색상 저장 완료 · 화면 새로고침 중");location.reload()}else setMessage("색상 저장 실패")};
 const report=async()=>{try{const result=await job("/api/jobs/report",{start,end});window.open(`/api/config/report/${encodeURIComponent(result.filename)}`,"_blank")}catch(e){setMessage(String(e))}};
 const toggleTarget=(target:string)=>setScheduler({...scheduler,targets:scheduler.targets.includes(target)?scheduler.targets.filter(x=>x!==target):[...scheduler.targets,target]});
 return <><header className="topbar"><div><p className="breadcrumb">System / Config</p><h1>Config</h1></div><span>{message}</span></header><section className="config-grid">
 <article className="config-card"><h2>Cache Data</h2><div className="config-range"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><b>~</b><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><button disabled={running} onClick={()=>refresh("detections")}>Detection 데이터 최신화</button><button disabled={running} onClick={()=>refresh("inbound")}>Inbound Mail 데이터 최신화</button><button disabled={running} onClick={()=>refresh("endpoints")}>Endpoint 데이터 최신화</button><button disabled={running} onClick={()=>refresh("organizations")}>Organization / User 데이터 최신화</button></article>
 <article className="config-card"><h2>Auto Refresh Scheduler</h2><label className="scheduler-enable"><input type="checkbox" checked={scheduler.enabled} onChange={e=>setScheduler({...scheduler,enabled:e.target.checked})}/> 스케줄러 사용</label><label>Interval <input type="number" min="1" max="1440" value={scheduler.interval} onChange={e=>setScheduler({...scheduler,interval:Number(e.target.value)})}/> min</label><div className="scheduler-targets">{[["detections","Detection - XDR"],["inbound","Inbound Mail"],["endpoints","Endpoint"],["organizations","Organization/User"]].map(([key,label])=><label key={key}><input type="checkbox" checked={scheduler.targets.includes(key)} onChange={()=>toggleTarget(key)}/>{label}</label>)}</div><button onClick={saveScheduler}>스케줄러 설정 저장</button><p><b>Last Run</b><span>{scheduler.lastRun||"-"}</span></p><small>{scheduler.lastResult}</small></article>
 <article className="config-card"><h2>Cache Status</h2>{status&&Object.entries(status.sources).map(([name,item])=><p key={name}><b>{name}</b><span className={item.exists?"ok":"missing"}>{item.exists?`${item.files} files · ${(item.bytes/1048576).toFixed(1)} MB`:"없음"}</span></p>)}</article>
 <article className="config-card"><h2>Index Data</h2>{status&&Object.entries(status.indexes).map(([name,item])=><p key={name}><b>{name}</b><span className={item.exists?"ok":"missing"}>{item.exists?`${(item.bytes/1048576).toFixed(1)} MB`:"인덱스 없음"}</span></p>)}<button onClick={load}>Data Health Check</button></article>
 <article className="config-card theme-card"><h2>UI Color Settings</h2><div className="theme-colors">{Object.entries(themeLabels).map(([key,label])=><label key={key}><span>{label}</span><input type="color" value={theme[key]||"#000000"} onChange={e=>setTheme({...theme,[key]:e.target.value})}/><code>{theme[key]}</code></label>)}</div><button onClick={saveTheme}>색상 설정 저장 및 적용</button></article>
 <article className="config-card"><h2>Export & Security Report</h2><div className="config-range"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><b>~</b><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>{[["detections","Detection"],["xdr","Email XDR"],["inbound","Inbound Mail"],["outbound","Outbound Mail"],["dlp","DLP File"]].map(([kind,label])=><button key={kind} onClick={()=>window.open(`/api/config/export/${kind}?start=${start}&end=${end}`,"_blank")}>{label} CSV</button>)}<button className="report-button" disabled={running} onClick={report}>Security Report PDF</button><small>CSV는 exports, PDF는 reports 폴더에도 저장됩니다.</small></article>
 <article className="config-card"><h2>Runtime & Logs</h2><p><b>로그 경로</b><span>{status?.logs}</span></p><p><b>Launcher</b><span>launcher.log</span></p><p><b>Backend Error</b><span>web_errors.log</span></p><p><b>Requests</b><span>web_app.log</span></p></article>
 </section></>}
