import {useEffect,useState} from "react";
type Status={sources:Record<string,{exists:boolean;files:number;bytes:number;latest:number|null}>;indexes:Record<string,{exists:boolean;bytes:number}>;logs:string};type TargetStatus={time:string;status:string;message:string};type Scheduler={enabled:boolean;interval:number;targets:string[];lastRun:string|null;lastResult:string;nextRun:string|null;running:boolean;targetStatus:Record<string,TargetStatus>;phase:string;currentTarget:string|null;currentMessage:string};
const themeLabels:Record<string,string>={Primary_Blue:"메인 강조색",Primary_Blue_Dark:"강조 어두운 색",UI_Background:"앱 배경",UI_Surface:"카드 배경",Card_Border:"카드 테두리",Card_Title_Text:"카드 제목",Table_Header_Background:"테이블 헤더 배경",Table_Header_Text:"테이블 헤더 글씨",Table_Selection_Background:"선택 행 배경",Table_Selection_Text:"선택 행 글씨",Status_Success_Text:"성공",Status_Fail_Text:"실패",Threat_trend_Detection:"Detection 그래프",Threat_trend_Detection_XDR:"Email XDR 그래프",Threat_trend_Email:"Inbound 그래프",Threat_trend_Outbound_Mail:"Outbound 그래프",Threat_trend_File:"File 그래프"};
export function ConfigPage(){
 const today=new Date().toISOString().slice(0,10),week=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const [status,setStatus]=useState<Status|null>(null),[start,setStart]=useState(week),[end,setEnd]=useState(today),[dlpStart,setDlpStart]=useState(week),[dlpEnd,setDlpEnd]=useState(today),[outboundStart,setOutboundStart]=useState(week),[outboundEnd,setOutboundEnd]=useState(today),[message,setMessage]=useState(""),[running,setRunning]=useState(false),[scheduler,setScheduler]=useState<Scheduler>({enabled:false,interval:10,targets:[],lastRun:null,lastResult:"-",nextRun:null,running:false,targetStatus:{},phase:"idle",currentTarget:null,currentMessage:"대기 중"}),[theme,setTheme]=useState<Record<string,string>>({});
 const load=()=>Promise.all([fetch("/api/config/status").then(r=>r.json()),fetch("/api/config/scheduler").then(r=>r.json()),fetch("/api/config/theme").then(r=>r.json())]).then(([a,b,c])=>{setStatus(a.data);setScheduler(b.data);setTheme(c.data)});useEffect(()=>{load();const timer=setInterval(()=>Promise.all([fetch("/api/config/scheduler").then(r=>r.json()),fetch("/api/config/status").then(r=>r.json())]).then(([p,s])=>{setScheduler(current=>({...current,lastRun:p.data.lastRun,lastResult:p.data.lastResult,nextRun:p.data.nextRun,running:p.data.running,targetStatus:p.data.targetStatus||{},phase:p.data.phase||"idle",currentTarget:p.data.currentTarget,currentMessage:p.data.currentMessage||"대기 중"}));setStatus(s.data)}),3000);return()=>clearInterval(timer)},[]);
 const job=async(url:string,body:unknown)=>{setRunning(true);try{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message);for(;;){await new Promise(x=>setTimeout(x,800));const j=await fetch(`/api/jobs/${p.data.id}`).then(x=>x.json());setMessage(j.data.message);if(j.data.status==="completed"){await load();setRunning(false);return j.data.result}if(j.data.status==="failed")throw new Error(j.data.error?.message)}}finally{setRunning(false)}};
 const refresh=(target:string)=>job(`/api/jobs/refresh/${target}`,["detections","inbound"].includes(target)?{start,end}:target==="dlp"?{start:dlpStart,end:dlpEnd}:target==="outbound"?{start:outboundStart,end:outboundEnd}:{}).catch(e=>setMessage(String(e)));
 const saveScheduler=async()=>{const r=await fetch("/api/config/scheduler",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(scheduler)}),payload=await r.json();if(!r.ok)throw new Error(payload?.error?.message||"스케줄러 저장 실패");setScheduler(payload.data);setMessage(`스케줄러 저장 완료 · 다음 실행 ${payload.data.nextRun||"중지"}`)};
 const runScheduler=async()=>{const r=await fetch("/api/config/scheduler/run",{method:"POST"}),payload=await r.json();setMessage(payload.data.accepted?"스케줄러 즉시 실행을 시작했습니다.":"이미 스케줄러가 실행 중입니다.");if(payload.data.accepted)setScheduler(current=>({...current,running:true,phase:"collecting",currentTarget:null,currentMessage:"수집 작업 준비 중",lastResult:"수집 작업 실행 중"}))};
 const saveTheme=async()=>{const r=await fetch("/api/config/theme",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(theme)});if(r.ok){setMessage("색상 저장 완료 · 화면 새로고침 중");location.reload()}else setMessage("색상 저장 실패")};
 const report=async()=>{try{const result=await job("/api/jobs/report",{start,end});window.open(`/api/config/report/${encodeURIComponent(result.filename)}`,"_blank")}catch(e){setMessage(String(e))}};
 const toggleTarget=(target:string)=>setScheduler({...scheduler,targets:scheduler.targets.includes(target)?scheduler.targets.filter(x=>x!==target):[...scheduler.targets,target]});
 return <><header className="topbar"><div><p className="breadcrumb">System / Config</p><h1>Config</h1></div><span>{message}</span></header><section className="config-grid">
 <article className="config-card cache-data-card"><h2>Cache Data</h2><div className="refresh-row"><div className="config-range"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><b>~</b><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><button disabled={running} onClick={()=>refresh("detections")}>Detection 데이터 최신화</button></div><div className="refresh-row"><div className="config-range"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><b>~</b><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><button disabled={running} onClick={()=>refresh("inbound")}>Inbound Mail 데이터 최신화</button></div><div className="refresh-row"><div className="config-range"><input type="date" value={dlpStart} onChange={e=>setDlpStart(e.target.value)}/><b>~</b><input type="date" value={dlpEnd} onChange={e=>setDlpEnd(e.target.value)}/></div><button disabled={running} onClick={()=>refresh("dlp")}>DLP 기간 최신화</button></div><div className="refresh-row"><div className="config-range"><input type="date" value={outboundStart} onChange={e=>setOutboundStart(e.target.value)}/><b>~</b><input type="date" value={outboundEnd} onChange={e=>setOutboundEnd(e.target.value)}/></div><button disabled={running} onClick={()=>refresh("outbound")}>Outbound Mail 기간 최신화</button></div><div className="collector-buttons"><button disabled={running} onClick={()=>refresh("endpoints")}>Endpoint 데이터 최신화</button><button disabled={running} onClick={()=>refresh("organizations")}>Organization 데이터 최신화</button><button disabled={running} onClick={()=>refresh("users")}>User 데이터 최신화</button></div></article>
 <article className="config-card scheduler-card"><h2>Auto Refresh Scheduler</h2>{scheduler.running&&<div className={`scheduler-progress ${scheduler.phase}`}><b>{scheduler.phase==="indexing"?"INDEXING":"COLLECTING"} · {scheduler.currentTarget||"준비"}</b><span>{scheduler.currentMessage}</span><i/></div>}<label className="scheduler-enable"><input type="checkbox" checked={scheduler.enabled} onChange={e=>setScheduler({...scheduler,enabled:e.target.checked})}/> 스케줄러 사용</label><label>Interval <input type="number" min="1" max="1440" value={scheduler.interval} onChange={e=>setScheduler({...scheduler,interval:Number(e.target.value)})}/> min</label><div className="scheduler-targets">{[["detections","Detection + Email XDR"],["inbound","Inbound Mail"],["dlp","DLP"],["outbound","Outbound Mail"],["endpoints","Endpoint"],["organizations","Organization"],["users","User"]].map(([key,label])=><label key={key}><input type="checkbox" checked={scheduler.targets.includes(key)} onChange={()=>toggleTarget(key)}/><span>{label}</span><small className={scheduler.targetStatus[key]?.status==="SUCCESS"?"ok":"missing"}>{scheduler.targetStatus[key]?.time||"실행 기록 없음"}</small></label>)}</div><div className="scheduler-actions"><button onClick={saveScheduler}>스케줄러 설정 저장</button><button className="primary-action" disabled={scheduler.running} onClick={runScheduler}>{scheduler.running?"실행 중...":"지금 실행"}</button></div><p><b>Next Run</b><span>{scheduler.nextRun||"-"}</span></p><p><b>Last Run</b><span>{scheduler.lastRun||"-"}</span></p><small>{scheduler.lastResult}</small><small>모든 수집 작업 후 Sensitive/Timeline 인덱스와 Dashboard 사전 집계를 자동 갱신합니다.</small></article>
 <article className="config-card"><h2>Cache Status</h2>{status&&Object.entries(status.sources).map(([name,item])=><p key={name}><b>{name}</b><span className={item.exists?"ok":"missing"}>{item.exists?`${item.files} files · ${(item.bytes/1048576).toFixed(1)} MB · ${item.latest?new Date(item.latest*1000).toLocaleString("ko-KR"):"-"}`:"없음"}</span></p>)}</article>
 <article className="config-card"><h2>Index Data</h2>{status&&Object.entries(status.indexes).map(([name,item])=><p key={name}><b>{name}</b><span className={item.exists?"ok":"missing"}>{item.exists?`${(item.bytes/1048576).toFixed(1)} MB`:"인덱스 없음"}</span></p>)}<button className="primary-action" disabled={running} onClick={()=>job("/api/jobs/index",{}).catch(e=>setMessage(String(e)))}>전체 캐시 데이터 인덱싱</button><button onClick={load}>Data Health Check</button><small>원본 캐시는 유지하고 새 SQLite 인덱스를 만든 뒤 안전하게 교체합니다.</small></article>
 <article className="config-card theme-card"><h2>UI Color Settings</h2><div className="theme-colors">{Object.entries(themeLabels).map(([key,label])=><label key={key}><span>{label}</span><input type="color" value={theme[key]||"#000000"} onChange={e=>setTheme({...theme,[key]:e.target.value})}/><code>{theme[key]}</code></label>)}</div><button onClick={saveTheme}>색상 설정 저장 및 적용</button></article>
 <article className="config-card"><h2>Export & Security Report</h2><div className="config-range"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><b>~</b><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>{[["detections","Detection"],["xdr","Email XDR"],["inbound","Inbound Mail"],["outbound","Outbound Mail"],["dlp","DLP File"]].map(([kind,label])=><button key={kind} onClick={()=>window.open(`/api/config/export/${kind}?start=${start}&end=${end}`,"_blank")}>{label} CSV</button>)}<button className="report-button" disabled={running} onClick={report}>Security Report PDF</button><small>CSV는 exports, PDF는 reports 폴더에도 저장됩니다.</small></article>
 <article className="config-card"><h2>Runtime & Logs</h2><p><b>로그 경로</b><span>{status?.logs}</span></p><p><b>Launcher</b><span>launcher.log</span></p><p><b>Backend Error</b><span>web_errors.log</span></p><p><b>Requests</b><span>web_app.log</span></p></article>
 </section></>}
