import { useEffect, useState } from "react";

type Kind="files"|"sites";
type Category={id:string;name:string;keywords:string[];enabled:boolean;priority:number;description:string;updatedAt:string};
const empty=():Category=>({id:"",name:"",keywords:[],enabled:true,priority:10,description:"",updatedAt:""});

export function ContentManagementPage(){
 const [kind,setKind]=useState<Kind>("files"),[items,setItems]=useState<Category[]>([]),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[editing,setEditing]=useState<Category|null>(null),[form,setForm]=useState<Category>(empty()),[keywordText,setKeywordText]=useState(""),[saving,setSaving]=useState(false);
 const load=async(target:Kind=kind)=>{setLoading(true);try{const r=await fetch(`/api/config/content/${target}`),p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"콘텐츠 설정 조회 실패");setItems(p.data.categories||[])}catch(e){setMessage(String(e))}finally{setLoading(false)}};
 useEffect(()=>{load(kind)},[kind]);
 const changeKind=(target:Kind)=>{setKind(target);setQuery("");setModal(false)};
 const open=(item?:Category)=>{const value=item?{...item,keywords:[...item.keywords]}:empty();setEditing(item||null);setForm(value);setKeywordText(value.keywords.join("\n"));setMessage("");setModal(true)};
 const save=async()=>{setSaving(true);try{const body={...form,keywords:keywordText.split(/\r?\n|,/).map(value=>value.trim()).filter(Boolean)},url=editing?`/api/config/content/${kind}/${editing.id}`:`/api/config/content/${kind}`;const r=await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"저장 실패");setModal(false);await load(kind);setMessage("콘텐츠 규칙을 저장했습니다. 과거 데이터 반영은 General에서 전체 캐시 인덱싱을 수동 실행해주세요.")}catch(e){setMessage(String(e))}finally{setSaving(false)}};
 const remove=async(item:Category)=>{if(!confirm(`${item.name} 카테고리를 삭제하시겠습니까?`))return;const r=await fetch(`/api/config/content/${kind}/${item.id}`,{method:"DELETE"}),p=await r.json().catch(()=>null);if(!r.ok){setMessage(p?.error?.message||"삭제 실패");return}await load(kind);setMessage("카테고리를 삭제했습니다. Raw Data는 변경되지 않습니다.")};
 const needle=query.trim().toLocaleLowerCase(),filtered=items.filter(item=>!needle||item.name.toLocaleLowerCase().includes(needle)||item.description.toLocaleLowerCase().includes(needle)||item.keywords.some(keyword=>keyword.toLocaleLowerCase().includes(needle)));
 return <><header className="topbar"><div><p className="breadcrumb">System / Config / Content Management</p><h1>Content Management</h1></div><button className="refresh-button" onClick={()=>open()}>＋ 카테고리 추가</button></header>
 <section className="panel content-management"><div className="detection-tools exception-heading"><div><h2>민감 콘텐츠 분류 관리</h2><p>기존 매칭 방식은 유지하고 카테고리와 키워드만 관리합니다.</p></div><div className="source-filters exception-tabs"><button className={kind==="files"?"active":""} onClick={()=>changeKind("files")}>Sensitive Files</button><button className={kind==="sites"?"active":""} onClick={()=>changeKind("sites")}>Sensitive Sites</button></div></div>
 <div className="condition-list exception-condition-list"><div className="condition-row exception-filter-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="카테고리, 키워드 또는 설명 검색"/><span>{filtered.length.toLocaleString()}개 카테고리 · {filtered.reduce((sum,item)=>sum+item.keywords.length,0).toLocaleString()}개 {kind==="files"?"키워드":"도메인"}</span></div></div>{message&&<div className="error-banner content-message">{message}</div>}
 <div className="integration-grid content-card-grid">{loading?<div className="dashboard-state">콘텐츠 설정을 불러오는 중입니다...</div>:filtered.map(item=><article className="integration-card content-rule-card" key={item.id}><header><div><h2>{item.name}</h2><span>우선순위 {item.priority} · {item.keywords.length}개 규칙</span></div><b className={`integration-status ${item.enabled?"connected":"error"}`}><span>●</span>{item.enabled?"사용":"중지"}</b></header><p>{item.description||"설명 없음"}</p><div className="integration-tags content-keywords">{item.keywords.slice(0,12).map(keyword=><i key={keyword}>{keyword}</i>)}{item.keywords.length>12&&<i>+{item.keywords.length-12}</i>}</div><footer><div><small>{kind==="files"?"Sensitive Files":"Sensitive Sites"}</small></div><div className="integration-actions"><button onClick={()=>open(item)}>수정</button><button className="integration-delete" onClick={()=>remove(item)}>삭제</button></div></footer></article>)}{!loading&&!filtered.length&&<div className="integration-empty">검색 조건에 맞는 카테고리가 없습니다.</div>}</div></section>
 {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><section className="integration-modal content-modal"><header><div><p>{editing?"카테고리 수정":"새 카테고리"}</p><h2>{kind==="files"?"Sensitive Files":"Sensitive Sites"}</h2></div><button onClick={()=>setModal(false)}>×</button></header><div className="integration-form content-form"><label><span>카테고리명</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="분류 카테고리명"/></label><label><span>우선순위</span><input type="number" min="1" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}/><small>숫자가 작을수록 먼저 매칭합니다.</small></label><label className="content-keyword-input"><span>{kind==="files"?"키워드":"도메인 및 URL 패턴"}</span><textarea rows={10} value={keywordText} onChange={e=>setKeywordText(e.target.value)} placeholder={kind==="files"?"한 줄에 키워드 하나씩 입력":"한 줄에 도메인 하나씩 입력"}/></label><label><span>설명</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="카테고리 설명 (선택)"/></label><label className="integration-check"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>카테고리 사용</span></label></div>{message&&<div className="integration-modal-message">{message}</div>}<footer><button onClick={()=>setModal(false)}>취소</button><button className="primary-action" disabled={saving} onClick={save}>{saving?"저장 중...":"저장"}</button></footer></section></div>}</>;
}
