import { useEffect, useState } from "react";

type Pair = [string, number];
type SummaryRow = [string, Pair[]];
type Dashboard = { range: { start: string; end: string }; endpoints: { pc: number; server: number; total: number }; organization: { departments: number; users: number }; folderUsage: Record<string, number>; totals: Record<string, number>; comparison: Record<string, { previous: number | null; year: number | null }>; trend: { dates: string[]; series: Record<string, number[]> }; top: { files: Pair[]; hashes: Pair[]; hosts: Pair[]; rules: Pair[]; senders: Pair[] }; summary: Record<string, SummaryRow[]>; cache: string };
const colors: Record<string, string> = { "Detection - XDR": "var(--trend-detection)", "Email - XDR": "var(--trend-xdr)", "Inbound Mail": "var(--trend-email)", "Outbound Mail": "var(--trend-outbound)", File: "var(--trend-file)" };
let dashboardSnapshot: Dashboard | null = null;
const summaryTitles: Record<string, string> = { detection: "Detection - XDR Summary", xdr: "Email - XDR Summary", inbound: "Inbound Mail Summary", file: "File Summary" };

function Ranking({ title, rows }: { title: string; rows: Pair[] }) { return <article className="dash-card ranking"><h2>{title}</h2>{rows.length === 0 ? <p>집계 데이터 없음</p> : <ol>{rows.map(([name, count]) => <li key={name}><span title={name}>{name}</span><b>({count.toLocaleString()})</b></li>)}</ol>}</article>; }
function bytes(value: number) { const units = ["B", "KB", "MB", "GB", "TB"]; let size = value; let unit = 0; while (size >= 1024 && unit < units.length - 1) { size /= 1024; unit += 1; } return `${size.toFixed(unit < 2 ? 0 : 1)} ${units[unit]}`; }
function Percent({ value }: { value: number | null }) { if (value === null) return <b className="same">신규</b>; const className = value > 0 ? "up" : value < 0 ? "down" : "same"; return <b className={className}>{value > 0 ? "▲" : value < 0 ? "▼" : "-"} {value > 0 ? "+" : ""}{value.toFixed(1)}%</b>; }
function Summary({ name, rows }: { name: string; rows: SummaryRow[] }) { return <article className="dash-card summary-card"><h2>{summaryTitles[name]}</h2>{rows.map(([label, values]) => <p key={label}><b>{label}</b> : {values.length ? `${values[0][0]} (${values[0][1].toLocaleString()})` : "None"}</p>)}</article>; }
function smoothPath(points: [number, number][]) { if (points.length < 2) return ""; return points.slice(1).reduce((path, point, index) => { const previous = points[index]; const before = points[Math.max(0, index - 1)]; const after = points[Math.min(points.length - 1, index + 2)]; const c1x = previous[0] + (point[0] - before[0]) / 6; const c1y = previous[1] + (point[1] - before[1]) / 6; const c2x = point[0] - (after[0] - previous[0]) / 6; const c2y = point[1] - (after[1] - previous[1]) / 6; return `${path} C ${c1x} ${c1y}, ${c2x} ${c2y}, ${point[0]} ${point[1]}`; }, `M ${points[0][0]} ${points[0][1]}`); }

export function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(dashboardSnapshot); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [visible, setVisible] = useState(Object.keys(colors));
  const load = async (rangeStart = "", rangeEnd = "") => { setLoading(true); setError(""); try { const params = rangeStart && rangeEnd ? `?start=${rangeStart}&end=${rangeEnd}` : ""; const response = await fetch(`/api/dashboard${params}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); dashboardSnapshot = payload.data; setData(payload.data); setStart(payload.data.range.start); setEnd(payload.data.range.end); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } };
  useEffect(() => { if (dashboardSnapshot) { setStart(dashboardSnapshot.range.start); setEnd(dashboardSnapshot.range.end); setLoading(false); } else load(); }, []);
  if (loading && !data) return <div className="dashboard-state">미리 집계된 Dashboard를 불러오는 중입니다...</div>;
  if (error && !data) return <div className="error-banner">Dashboard 조회 오류: {error}</div>;
  if (!data) return null;
  const maximum = Math.max(1, ...Object.entries(data.trend.series).filter(([name]) => visible.includes(name)).flatMap(([, values]) => values)); const width = 1000; const height = 225; const x = (index: number) => 30 + index * (width - 60) / Math.max(1, data.trend.dates.length - 1); const y = (value: number) => height - 30 - value / maximum * (height - 55);
  const topRows = Math.max(data.top.hosts.length, data.top.rules.length, data.top.senders.length);
  return <><header className="topbar dash-topbar"><div><p className="breadcrumb">Overview / Dashboard</p><h1>Dashboard</h1></div><div className="dashboard-range"><span>{data.range.start} ~ {data.range.end}</span><input type="date" value={start} onChange={(event) => setStart(event.target.value)} /><b>~</b><input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /><button disabled={loading || !start || !end} onClick={() => load(start, end)}>{loading ? "집계 중" : "적용"}</button><i>{data.cache === "pre-aggregated" ? "미리 집계됨" : "집계 완료"}</i></div></header>
    {error && <div className="error-banner">Dashboard 조회 오류: {error}</div>}
    <section className="dash-top"><div className="asset-stack"><article className="dash-card asset-card"><h2>▣ Endpoints</h2><dl><div><dt>PC</dt><dd>{data.endpoints.pc.toLocaleString()} 대</dd></div><div><dt>Server</dt><dd>{data.endpoints.server.toLocaleString()} 대</dd></div></dl></article><article className="dash-card asset-card"><h2>♧ Organization</h2><dl><div><dt>조직부서</dt><dd>{data.organization.departments.toLocaleString()} 개</dd></div><div><dt>사원 수</dt><dd>{data.organization.users.toLocaleString()} 명</dd></div></dl></article></div><Ranking title="▧ Top File" rows={data.top.files} /><Ranking title="# Top Hash" rows={data.top.hashes} /><article className="dash-card folder-card"><h2>▱ Folder Usage</h2>{Object.entries(data.folderUsage).map(([name, size]) => <p key={name}><span>{name}</span><b>{bytes(size)}</b></p>)}</article></section>
    <section className="dash-card threat-card"><h2>⌁ Threat Trend</h2><div className="threat-content"><div className="chart-area"><div className="trend-toggles">{Object.entries(colors).map(([name, color]) => <label key={name}><input type="checkbox" checked={visible.includes(name)} onChange={() => setVisible((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name])} /><i style={{ background: color }} />{name}</label>)}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Threat Trend"><defs>{Object.entries(colors).map(([name,color])=><linearGradient key={name} id={`area-${name.replaceAll(" ","").replaceAll("-","")}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".22"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient>)}</defs>{[0, .25, .5, .75, 1].map((part) => <line key={part} x1="30" x2={width - 30} y1={y(maximum * part)} y2={y(maximum * part)} className="grid-line" />)}{Object.entries(data.trend.series).filter(([name]) => visible.includes(name)).map(([name, values]) => {const points=values.map((value,index)=>[x(index),y(value)] as [number,number]),path=smoothPath(points),gradient=`area-${name.replaceAll(" ","").replaceAll("-","")}`;return <g key={name} className="trend-series"><path d={`${path} L ${points.at(-1)?.[0]} ${height-30} L ${points[0][0]} ${height-30} Z`} fill={`url(#${gradient})`} className="trend-area"/><path d={path} fill="none" stroke={colors[name]} strokeWidth="3.5" strokeLinecap="round" className="trend-wave"/>{values.map((value,index)=><g key={index} className="trend-point"><circle cx={x(index)} cy={y(value)} r="11" fill="transparent"/><circle cx={x(index)} cy={y(value)} r="4" fill="#fff" stroke={colors[name]} strokeWidth="3"/><g className="trend-tooltip" transform={`translate(${Math.min(width-105,Math.max(55,x(index)))},${Math.max(34,y(value)-18)})`}><rect x="-52" y="-31" width="104" height="25" rx="7"/><text y="-15">{name} · {value.toLocaleString()}</text></g></g>)}</g>})}{data.trend.dates.map((day, index) => <text key={day} x={x(index)} y={height - 7} className="axis-label">{day.slice(5)}</text>)}</svg></div><aside className="comparison"><header><span>직전기간 대비</span><span>전년 대비</span></header>{Object.entries(data.comparison).map(([name, values]) => <div key={name}><strong>{name}</strong><Percent value={values.previous} /><Percent value={values.year} /></div>)}</aside></div></section>
    <section className="dash-bottom"><article className="dash-card top-analysis"><h2>▥ Top Analysis</h2><table><thead><tr><th>Top Hostname</th><th>Top Rule</th><th>Top Sender IP</th></tr></thead><tbody>{Array.from({ length: topRows }, (_, index) => <tr key={index}><td>{data.top.hosts[index] ? `${data.top.hosts[index][0]} (${data.top.hosts[index][1]})` : ""}</td><td>{data.top.rules[index] ? `${data.top.rules[index][0]} (${data.top.rules[index][1]})` : ""}</td><td>{data.top.senders[index] ? `${data.top.senders[index][0]} (${data.top.senders[index][1]})` : ""}</td></tr>)}</tbody></table></article><div className="summary-grid">{Object.entries(data.summary).map(([name, rows]) => <Summary key={name} name={name} rows={rows} />)}</div></section>
  </>;
}
