import { useEffect, useState } from "react";

type Pair = [string, number];
type SummaryRow = [string, Pair[]];
type Dashboard = { range: { start: string; end: string }; endpoints: { pc: number; server: number; total: number }; organization: { departments: number; users: number }; folderUsage: Record<string, number>; totals: Record<string, number>; comparison: Record<string, { previous: number | null; year: number | null }>; trend: { dates: string[]; series: Record<string, number[]> }; top: { files: Pair[]; hashes: Pair[]; hosts: Pair[]; rules: Pair[]; senders: Pair[] }; summary: Record<string, SummaryRow[]>; cache: string };
const colors: Record<string, string> = { "Detection - XDR": "var(--trend-detection)", "Email - XDR": "var(--trend-xdr)", "Inbound Mail": "var(--trend-email)", "Outbound Mail": "var(--trend-outbound)", File: "var(--trend-file)" };
let dashboardSnapshot: Dashboard | null = null;
const summaryTitles: Record<string, string> = { detection: "Detection - XDR Summary", xdr: "Email - XDR Summary", inbound: "Inbound Mail Summary", file: "File Summary" };

function Ranking({ title, rows }: { title: string; rows: Pair[] }) { return <article className="dash-card ranking"><h2>{title}</h2>{rows.length === 0 ? <p>집계 데이터 없음</p> : <ol>{rows.map(([name, count]) => <li key={name}><span title={name}>{name}</span><b>({count.toLocaleString()})</b></li>)}</ol>}</article>; }
function bytes(value: number) { const units = ["B", "KB", "MB", "GB", "TB"]; let size = value; let unit = 0; while (size >= 1024 && unit < units.length - 1) { size /= 1024; unit += 1; } return `${size.toFixed(unit < 2 ? 0 : 1)} ${units[unit]}`; }
function Percent({ value }: { value: number | null }) { if (value === null) return <b className="same">신규</b>; const className = value > 0 ? "up" : value < 0 ? "down" : "same"; return <b className={className}>{value > 0 ? "▲" : value < 0 ? "▼" : "-"} {value > 0 ? "+" : ""}{value.toFixed(1)}%</b>; }
function Summary({ name, rows }: { name: string; rows: SummaryRow[] }) { return <article className="dash-card summary-card"><h2>{summaryTitles[name]}</h2>{rows.map(([label, values]) => <p key={label}><b>{label}</b> : {values.length ? `${values[0][0]} (${values[0][1].toLocaleString()})` : "None"}</p>)}</article>; }
function smoothPath(points: [number, number][]) { if (points.length < 2) return ""; return points.slice(1).reduce((path, point, index) => { const previous = points[index]; const before = points[Math.max(0, index - 1)]; const after = points[Math.min(points.length - 1, index + 2)]; const c1x = previous[0] + (point[0] - before[0]) / 6; const c1y = previous[1] + (point[1] - before[1]) / 6; const c2x = point[0] - (after[0] - previous[0]) / 6; const c2y = point[1] - (after[1] - previous[1]) / 6; return `${path} C ${c1x} ${c1y}, ${c2x} ${c2y}, ${point[0]} ${point[1]}`; }, `M ${points[0][0]} ${points[0][1]}`); }

function TrendChart({data,visible,setVisible}:{data:Dashboard;visible:string[];setVisible:(value:string[])=>void}) {
  const width=1000,height=250,active=Object.entries(data.trend.series).filter(([name])=>visible.includes(name));
  const maximum=Math.max(1,...active.flatMap(([,values])=>values));
  const x=(index:number)=>42+index*(width-84)/Math.max(1,data.trend.dates.length-1),y=(value:number)=>height-34-value/maximum*(height-70);
  const columnWidth=(width-84)/Math.max(1,data.trend.dates.length-1),tooltipHeight=34+active.length*18;
  return <div className="chart-area"><div className="trend-toggles">{Object.entries(colors).map(([name,color])=><label key={name}><input type="checkbox" checked={visible.includes(name)} onChange={()=>setVisible(visible.includes(name)?visible.filter(item=>item!==name):[...visible,name])}/><i style={{background:color}}/>{name}</label>)}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="날짜별 전체 보안 솔루션 추세">
    <defs>{Object.entries(colors).map(([name,color])=><linearGradient key={name} id={`area-${name.replaceAll(" ","").replaceAll("-","")}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".34"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient>)}</defs>
    {[0,.25,.5,.75,1].map(part=><line key={part} x1="42" x2={width-42} y1={y(maximum*part)} y2={y(maximum*part)} className="grid-line"/>)}
    {active.map(([name,values])=>{const points=values.map((value,index)=>[x(index),y(value)] as [number,number]),path=smoothPath(points),gradient=`area-${name.replaceAll(" ","").replaceAll("-","")}`;return <g key={name} className="trend-series"><path d={`${path} L ${points.at(-1)?.[0]} ${height-34} L ${points[0][0]} ${height-34} Z`} fill={`url(#${gradient})`} className="trend-area"/><path d={path} fill="none" stroke={colors[name]} strokeWidth="3.5" strokeLinecap="round" className="trend-wave"/>{values.map((value,index)=><circle key={index} cx={x(index)} cy={y(value)} r="4" fill="var(--surface)" stroke={colors[name]} strokeWidth="3" className="trend-dot"/>)}</g>})}
    {data.trend.dates.map((day,index)=>{const tooltipX=Math.min(width-202,Math.max(8,x(index)-94));return <g key={day} className="day-hover"><rect x={x(index)-columnWidth/2} y="8" width={columnWidth} height={height-28} fill="transparent"/><line x1={x(index)} x2={x(index)} y1="18" y2={height-34} className="hover-guide"/><g className="day-tooltip" transform={`translate(${tooltipX},12)`}><rect width="194" height={tooltipHeight} rx="12"/><text x="14" y="21" className="tooltip-date">{day}</text>{active.map(([name,values],row)=><g key={name} transform={`translate(0,${32+row*18})`}><circle cx="16" cy="0" r="4" fill={colors[name]}/><text x="28" y="4" className="tooltip-name">{name}</text><text x="180" y="4" className="tooltip-value">{(values[index]??0).toLocaleString()}</text></g>)}</g></g>})}
    {data.trend.dates.map((day,index)=><text key={day} x={x(index)} y={height-8} className="axis-label">{day.slice(5)}</text>)}
  </svg></div>;
}

export function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(dashboardSnapshot); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [visible, setVisible] = useState(Object.keys(colors));
  const load = async (rangeStart = "", rangeEnd = "") => { setLoading(true); setError(""); try { const params = rangeStart && rangeEnd ? `?start=${rangeStart}&end=${rangeEnd}` : ""; const response = await fetch(`/api/dashboard${params}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); dashboardSnapshot = payload.data; setData(payload.data); setStart(payload.data.range.start); setEnd(payload.data.range.end); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } };
  useEffect(() => { if (dashboardSnapshot) { setStart(dashboardSnapshot.range.start); setEnd(dashboardSnapshot.range.end); setLoading(false); } else load(); }, []);
  if (loading && !data) return <div className="dashboard-state">미리 집계된 Dashboard를 불러오는 중입니다...</div>;
  if (error && !data) return <div className="error-banner">Dashboard 조회 오류: {error}</div>;
  if (!data) return null;
  const topRows = Math.max(data.top.hosts.length, data.top.rules.length, data.top.senders.length);
  return <><header className="topbar dash-topbar"><div><p className="breadcrumb">Overview / Dashboard</p><h1>Dashboard</h1></div><div className="dashboard-range"><span>{data.range.start} ~ {data.range.end}</span><input type="date" value={start} onChange={(event) => setStart(event.target.value)} /><b>~</b><input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /><button disabled={loading || !start || !end} onClick={() => load(start, end)}>{loading ? "집계 중" : "적용"}</button><i>{data.cache === "pre-aggregated" ? "미리 집계됨" : "집계 완료"}</i></div></header>
    {error && <div className="error-banner">Dashboard 조회 오류: {error}</div>}
    <section className="dash-top"><div className="asset-stack"><article className="dash-card asset-card"><h2>▣ Endpoints</h2><dl><div><dt>PC</dt><dd>{data.endpoints.pc.toLocaleString()} 대</dd></div><div><dt>Server</dt><dd>{data.endpoints.server.toLocaleString()} 대</dd></div></dl></article><article className="dash-card asset-card"><h2>♧ Organization</h2><dl><div><dt>조직부서</dt><dd>{data.organization.departments.toLocaleString()} 개</dd></div><div><dt>사원 수</dt><dd>{data.organization.users.toLocaleString()} 명</dd></div></dl></article></div><Ranking title="▧ Top File" rows={data.top.files} /><Ranking title="# Top Hash" rows={data.top.hashes} /><article className="dash-card folder-card"><h2>▱ Folder Usage</h2>{Object.entries(data.folderUsage).map(([name, size]) => <p key={name}><span>{name}</span><b>{bytes(size)}</b></p>)}</article></section>
    <section className="dash-card threat-card"><h2>⌁ Threat Trend</h2><div className="threat-content"><TrendChart data={data} visible={visible} setVisible={setVisible}/><aside className="comparison"><header><span>직전기간 대비</span><span>전년 대비</span></header>{Object.entries(data.comparison).map(([name, values]) => <div key={name}><strong>{name}</strong><Percent value={values.previous} /><Percent value={values.year} /></div>)}</aside></div></section>
    <section className="dash-bottom"><article className="dash-card top-analysis"><h2>▥ Top Analysis</h2><table><thead><tr><th>Top Hostname</th><th>Top Rule</th><th>Top Sender IP</th></tr></thead><tbody>{Array.from({ length: topRows }, (_, index) => <tr key={index}><td>{data.top.hosts[index] ? `${data.top.hosts[index][0]} (${data.top.hosts[index][1]})` : ""}</td><td>{data.top.rules[index] ? `${data.top.rules[index][0]} (${data.top.rules[index][1]})` : ""}</td><td>{data.top.senders[index] ? `${data.top.senders[index][0]} (${data.top.senders[index][1]})` : ""}</td></tr>)}</tbody></table></article><div className="summary-grid">{Object.entries(data.summary).map(([name, rows]) => <Summary key={name} name={name} rows={rows} />)}</div></section>
  </>;
}
