import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";

type Row=Record<string,string>;
const columns:[string,string][]=[["time","Time"],["severity","Severity"],["rule","Rule"],["sourceIp","Source IP"],["sourcePort","Source Port"],["destinationIp","Destination IP"],["destinationPort","Destination Port"],["protocol","Protocol"],["application","Application"],["url","URL / Domain"],["action","Action"],["threat","Threat"]];
const detailFields:[string,string][]=[["sourceCountry","Source Country"],["destinationCountry","Destination Country"],["sourceZone","Source Zone"],["destinationZone","Destination Zone"],["deviceName","Device Name"],["deviceModel","Device Model"],["deviceSerial","Device Serial"],["logType","Log Type"],["logComponent","Log Component"],["logSubtype","Log Subtype"],["eventType","Event Type"],["eventId","Event ID"],["hits","Hits"],["processUser","Process User"],["filePath","File Path"],["processId","Process ID"],["processHash","Process Hash"],["threatFeed","Threat Feed"],["mitreTactic","MITRE Tactic"],["mitreTechnique","MITRE Technique"],["hostname","Hostname"],["user","User"],["dept","Department"]];
const today=()=>new Date().toISOString().slice(0,10),week=()=>new Date(Date.now()-6*86400000).toISOString().slice(0,10);

export function FirewallDetectionPage(){
 const [params,setParams]=useSearchParams(),[start,setStart]=useState(params.get("from")||week()),[end,setEnd]=useState(params.get("to")||today()),[field,setField]=useState(params.get("field")||"all"),[query,setQuery]=useState(params.get("q")||""),[page,setPage]=useState(1),[sort,setSort]=useState("time"),[direction,setDirection]=useState("desc"),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[detail,setDetail]=useState<{summary:Row;raw:unknown}|null>(null);
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>{setLoading(true);const conditions=query.trim()?[{field,query:query.trim()}]:[],search=new URLSearchParams({start,end,conditions:JSON.stringify(conditions),page:String(page),pageSize:"50",sort,direction});fetch(`/api/firewall-detections?${search}`,{signal:controller.signal}).then(r=>r.json()).then(payload=>{setRows(payload.data?.items||[]);setTotal(payload.data?.pagination?.total||0)}).finally(()=>setLoading(false))},300);return()=>{clearTimeout(timer);controller.abort()}},[start,end,field,query,page,sort,direction]);
 useEffect(()=>{const next=new URLSearchParams();next.set("from",start);next.set("to",end);if(query){next.set("field",field);next.set("q",query)}setParams(next,{replace:true})},[start,end,field,query]);
 const changeSort=(key:string)=>{if(sort===key)setDirection(value=>value==="asc"?"desc":"asc");else{setSort(key);setDirection("asc")}setPage(1)};
 const open=async(row:Row)=>{const payload=await fetch(`/api/firewall-detections/${row.id}?start=${start}&end=${end}`).then(r=>r.json());if(payload.data)setDetail(payload.data)};
 const pages=Math.max(1,Math.ceil(total/50));
 return <><header className="topbar"><div><p className="breadcrumb">Detection / Firewall</p><h1>Firewall Detection</h1></div><div className="date-range"><label>시작<input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(1)}}/></label><b>~</b><label>종료<input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(1)}}/></label></div></header><section className="panel detection-table"><div className="detection-tools"><div><h2>Firewall Detection</h2><p>Sophos Detection Raw의 sensor.type=firewall 이벤트</p></div><span>총 {total.toLocaleString()}건</span></div><div className="condition-list"><div className="condition-row"><select value={field} onChange={e=>setField(e.target.value)}><option value="all">ALL</option>{columns.map(([key,label])=><option key={key} value={key}>{label}</option>)}<option value="rawData">RawData</option></select><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="검색어 입력"/><button onClick={()=>setQuery("")}>×</button></div></div><div className="table-wrap"><table><thead><tr>{columns.map(([key,label])=><th key={key}><button className="sort-button" onClick={()=>changeSort(key)}>{label}<span>{sort===key?(direction==="asc"?"↑":"↓"):"↕"}</span></button></th>)}</tr></thead><tbody>{loading?<tr><td colSpan={12} className="state-cell">Firewall 이벤트 조회 중...</td></tr>:rows.length===0?<tr><td colSpan={12} className="state-cell">조건에 일치하는 Firewall 이벤트가 없습니다.</td></tr>:rows.map(row=><tr key={row.id} onClick={()=>open(row)}>{columns.map(([key])=><td key={key}>{row[key]||""}</td>)}</tr>)}</tbody></table></div><footer className="pagination"><span>페이지당 50개</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>이전</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(page+1)}>다음</button></div></footer></section>{detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="detail-modal firewall-detection-detail" onClick={e=>e.stopPropagation()}><header><div><span>Firewall Detection Detail</span><h2>{detail.summary.rule||"Firewall Event"}</h2></div><button onClick={()=>setDetail(null)}>×</button></header><div className="firewall-detail-grid">{[...columns,...detailFields].map(([key,label])=><p key={key}><b>{label}</b><span>{detail.summary[key]||"-"}</span></p>)}</div><pre>{JSON.stringify(detail.raw,null,2)}</pre></section></div>}</>;
}
