import { useState } from "react";

type Site = { input: string; network: string; site: string; category: string };
type FirewallResult = { firewall: string; available: boolean; checkedAt?: string; error?: string; policy: { state: string; orderReliable?: boolean; matchedRule?: { rule: string; status: string; action: string; sourceMatch: string; destinationMatch: string }; matches?: { rule: string; action: string }[] }; routing: { destination: Record<string,string>|null; return: Record<string,string>|null; error?: string } };
type Result = { source: Site; destination: Site; protocol: string; port: number; path: string[]; partialPath: boolean; firewalls: FirewallResult[]; checkedAt: string };

const policyLabel: Record<string,string> = { allow:"정책 허용 확인",deny:"차단 정책 확인",matched:"정책 일치",missing:"정책 누락",partial:"Partial Match",disabled:"비활성 정책",order_check_required:"Rule Order 확인 필요",unavailable:"조회 불가" };
const tone = (state:string) => state === "allow" ? "success" : state === "deny" || state === "missing" ? "fail" : "exists";
const routeLabel = (route: Record<string,string>|null) => route
  ? [route.network, route.interface && `Interface: ${route.interface}`, route.gateway && `Gateway: ${route.gateway}`].filter(Boolean).join("\n")
  : "Static Route에서 미확인";

export function FirewallPathCheckPage(){
  const [source,setSource]=useState("101.1.0.50"),[destination,setDestination]=useState("100.1.2.10"),[protocol,setProtocol]=useState("TCP"),[port,setPort]=useState("389"),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const run=async(refresh=false)=>{setLoading(true);setError("");try{const response=await fetch("/api/firewall/path-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source,destination,protocol,port:Number(port),refresh})}),payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message||"Path Check 실패");setResult(payload.data)}catch(reason){setError(String(reason))}finally{setLoading(false)}};
  const node=(name:string,subtitle:string,firewall?:FirewallResult)=><article className="panel"><b>{name}</b><small>{subtitle}</small>{firewall&&<><span className={`result-pill ${tone(firewall.policy.state)}`}>{policyLabel[firewall.policy.state]||firewall.policy.state}</span><span className={`result-pill ${firewall.routing.destination?"success":"exists"}`}>{firewall.routing.destination?"Static Route 확인":"Static Route 미확인"}</span></>}</article>;
  const allPoliciesConfirmed = Boolean(result?.firewalls.length) && result!.firewalls.every(item=>item.policy.state === "allow");
  const allRoutesConfirmed = Boolean(result?.firewalls.length) && result!.firewalls.every(item=>item.routing.destination && item.routing.return);
  return <><header className="topbar"><div><p className="breadcrumb">Response / Firewall Path Check</p><h1>Firewall Path Check</h1></div>{result&&<div><small>마지막 확인</small><b>{new Date(result.checkedAt).toLocaleString()}</b></div>}</header>
    <section className="panel path-check-form"><div className="integration-form-pair"><label>Source IP / CIDR<input value={source} onChange={e=>setSource(e.target.value)} placeholder="101.1.0.50"/></label><label>Destination IP / CIDR<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="100.1.2.10"/></label></div><div className="integration-form-pair"><label>Protocol<select value={protocol} onChange={e=>setProtocol(e.target.value)}><option>TCP</option><option>UDP</option></select></label><label>Destination Port<input type="number" min="1" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label></div><div className="firewall-buttons"><button className="primary-action" disabled={loading} onClick={()=>run(false)}>{loading?"확인 중...":"Path Check"}</button>{result&&<button disabled={loading} onClick={()=>run(true)}>최신 정보 다시 조회</button>}</div>{error&&<div className="error-banner">{error}</div>}</section>
    {result&&<><section className="panel path-summary"><div><b>Source</b><strong>{result.source.input}</strong><span>{result.source.site} · {result.source.category||"Mapping 미확인"}</span></div><div><b>Destination</b><strong>{result.destination.input}</strong><span>{result.destination.site} · {result.destination.category||"Mapping 미확인"}</span></div><div><b>Service</b><strong>{result.protocol} / {result.port}</strong><span>{result.partialPath?"Path 일부만 확인 가능":"관리 Firewall Path 확인"}</span></div></section>
      <section className="path-diagram">{node(result.source.site,result.source.input)}{result.firewalls.map(item=><div className="path-segment" key={item.firewall}><i>▶</i>{node(`${item.firewall} Firewall`,item.available?"Configuration 확인":"조회 불가",item)}</div>)}<div className="path-segment"><i>▶</i>{node(result.destination.site,`${result.destination.input} · ${result.protocol}/${result.port}`)}</div></section>
      <section className="panel path-summary"><div><b>Policy Path</b><strong>{allPoliciesConfirmed?"Firewall Policy 확인됨":result.partialPath?"Path 일부만 확인 가능":"Firewall Policy 누락 또는 확인 필요"}</strong></div><div><b>Static Route</b><strong>{allRoutesConfirmed?"Static Route 확인됨":"Static Route에서 일치 경로 미확인"}</strong></div><div><b>판정 범위</b><strong>Configuration 기반 Path Check</strong><span>실제 패킷 연결성을 단정하지 않습니다.</span></div></section>
      <section className="panel firewall-results"><header><div><h2>Firewall별 상세 결과</h2><p>실제 패킷 테스트가 아닌 Configuration 기반 확인 결과입니다.</p></div></header><div className="table-wrap"><table><thead><tr><th>Firewall</th><th>Policy</th><th>Matched Rule</th><th>Source</th><th>Destination</th><th>Service</th><th>Action</th><th>Destination Route</th><th>Return Route</th></tr></thead><tbody>{result.firewalls.map(item=>{const rule=item.policy.matchedRule;return <tr key={item.firewall}><td>{item.firewall}</td><td><span className={`result-pill ${tone(item.policy.state)}`}>{policyLabel[item.policy.state]||item.policy.state}</span></td><td>{rule?.rule||item.policy.matches?.map(match=>match.rule).join(", ")||"-"}</td><td>{rule?.sourceMatch||"-"}</td><td>{rule?.destinationMatch||"-"}</td><td>{rule?"match":"-"}</td><td>{rule?.action||"-"}</td><td className="path-route-cell">{routeLabel(item.routing.destination)}</td><td className="path-route-cell">{routeLabel(item.routing.return)}</td></tr>})}</tbody></table></div></section></>}
  </>;
}
