import { useEffect, useState } from "react";

type Firewall = { name: string; configured: boolean };
type Result = { firewall: string; target: string; name: string; result: "SUCCESS" | "EXISTS" | "FAIL"; statusCode: string; message: string; error: string; raw: string };
type Group = { firewall: string; mode: string; group: string; members: string[]; statusCode: string; message: string; raw: string };

export function FirewallPage() {
  const [mode, setMode] = useState<"IP" | "DOMAIN">("IP"); const [input, setInput] = useState(""); const [firewalls, setFirewalls] = useState<Firewall[]>([]); const [selected, setSelected] = useState<string[]>([]); const [results, setResults] = useState<Result[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [raw, setRaw] = useState<unknown>(null); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [running, setRunning] = useState(false);
  useEffect(() => { fetch("/api/firewall/configuration").then((response) => response.json()).then((payload) => { setFirewalls(payload.data.firewalls); setSelected(payload.data.firewalls.filter((item: Firewall) => item.configured).map((item: Firewall) => item.name)); }).catch((reason) => setError(String(reason))); }, []);
  const targets = input.split(/\r?\n/).map((value) => value.trim()).filter(Boolean);
  const toggle = (name: string) => setSelected((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]);
  const poll = async (jobId: string, action: "create" | "groups") => { for (;;) { await new Promise((resolve) => window.setTimeout(resolve, 800)); const response = await fetch(`/api/jobs/${jobId}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); setStatus(payload.data.message); if (payload.data.status === "completed") { if (action === "create") setResults(payload.data.result.results); else setGroups(payload.data.result.groups); return; } if (payload.data.status === "failed") throw new Error(payload.data.error?.message || "Firewall 작업 실패"); } };
  const run = async (action: "create" | "groups") => { if (selected.length === 0) { setError("Firewall을 1개 이상 선택해주세요."); return; } if (action === "create" && !window.confirm(`${selected.join(", ")} 방화벽에 ${targets.length}개의 ${mode} 객체를 생성합니다. 계속할까요?`)) return; setRunning(true); setError(""); setStatus("작업 요청 중"); try { const response = await fetch("/api/jobs/firewall", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, mode, targets, firewalls: selected }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); await poll(payload.data.id, action); setStatus("완료"); } catch (reason) { setError(String(reason)); } finally { setRunning(false); } };
  const success = results.filter((item) => item.result === "SUCCESS");
  const copySuccess = async () => { await navigator.clipboard.writeText(success.map((item) => `${item.firewall}\t${item.target}\t${item.name}`).join("\n")); setStatus("성공 결과 복사 완료"); };
  return <><header className="topbar"><div><p className="breadcrumb">Response / Firewall</p><h1>Firewall Response</h1></div><span className="response-warning">실제 방화벽 변경 작업</span></header>
    <section className="firewall-workspace"><article className="panel firewall-input"><header><h2>차단 객체 생성</h2><select value={mode} onChange={(event) => setMode(event.target.value as "IP" | "DOMAIN")}><option>IP</option><option>DOMAIN</option></select></header><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder={mode === "IP" ? "차단할 IPv4를 한 줄에 하나씩 입력하세요.\n104.238.194.12" : "차단할 도메인을 한 줄에 하나씩 입력하세요.\nexample.com"} /><div className="firewall-targets"><h3>Firewall Target</h3>{firewalls.map((firewall) => <label className={firewall.configured ? "" : "disabled"} key={firewall.name}><input type="checkbox" disabled={!firewall.configured || running} checked={selected.includes(firewall.name)} onChange={() => toggle(firewall.name)} /><span>{firewall.name}</span><small>{firewall.configured ? "설정됨" : "환경설정 필요"}</small></label>)}</div><div className="firewall-buttons"><button className="danger-action" disabled={running || targets.length === 0} onClick={() => run("create")}>{running ? status : `${mode} 객체 생성`}</button><button disabled={running} onClick={() => setInput("")}>입력 초기화</button><button disabled={running} onClick={() => run("groups")}>선택 Firewall 그룹 조회</button></div></article>
      <article className="panel firewall-results"><header><div><h2>작업 결과</h2><p>성공 {success.length} · 중복 {results.filter((item) => item.result === "EXISTS").length} · 실패 {results.filter((item) => item.result === "FAIL").length}</p></div><button disabled={success.length === 0} onClick={copySuccess}>성공 결과 복사</button></header>{error && <div className="error-banner">{error}</div>}<div className="table-wrap"><table><thead><tr>{["Firewall", "Target", "Object Name", "Result", "Status Code", "Message", "Error"].map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{results.length === 0 ? <tr><td colSpan={7} className="state-cell">아직 실행 결과가 없습니다.</td></tr> : results.map((item, index) => <tr key={`${item.firewall}-${item.target}-${index}`} onDoubleClick={() => setRaw(item)}><td>{item.firewall}</td><td>{item.target}</td><td>{item.name}</td><td><span className={`result-pill ${item.result.toLowerCase()}`}>{item.result}</span></td><td>{item.statusCode}</td><td>{item.message}</td><td>{item.error}</td></tr>)}</tbody></table></div></article></section>
    {groups.length > 0 && <section className="panel group-results"><header><h2>Firewall Group View</h2><button onClick={() => setGroups([])}>닫기</button></header>{groups.map((group) => <article key={`${group.firewall}-${group.mode}`}><h3>{group.firewall} · {group.group}</h3><p>{group.members.length.toLocaleString()}개 객체</p><pre>{group.members.join("\n") || group.message || "멤버 없음"}</pre><button onClick={() => setRaw(group)}>Raw Response</button></article>)}</section>}
    {raw && <div className="modal-backdrop" onMouseDown={() => setRaw(null)}><section className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><header><h2>Firewall Raw Response</h2><button onClick={() => setRaw(null)}>×</button></header><pre>{JSON.stringify(raw, null, 2)}</pre></section></div>}
  </>;
}
