import { useEffect, useRef, useState } from "react";
type Seat={seat_id:string;x:number;y:number;w:number;h:number;name:string;user_id?:string;ip?:string;hostname?:string;dept?:string;email?:string;color?:string};type Candidate={name:string;user_id:string;hostname:string;ip:string;email:string;dept:string;source:string};type Layout={floors:Record<string,{image:string;seats:Seat[]}>};
export function LayoutPage(){
 const [layout,setLayout]=useState<Layout|null>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[floor,setFloor]=useState("18F"),[selected,setSelected]=useState(""),[search,setSearch]=useState(""),[edit,setEdit]=useState(false),[candidate,setCandidate]=useState(""),[message,setMessage]=useState(""),[scale,setScale]=useState(1);const imageRef=useRef<HTMLImageElement>(null),canvasRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{fetch("/api/layout").then(r=>r.json()).then(p=>{setLayout(p.data.layout);setCandidates(p.data.candidates)})},[]);
 useEffect(()=>{const resize=()=>{const image=imageRef.current,canvas=canvasRef.current;if(image&&canvas&&image.naturalWidth)setScale(canvas.clientWidth/image.naturalWidth)};window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[]);
 if(!layout)return <div className="dashboard-state">좌석 배치도를 불러오는 중입니다...</div>;const seats=layout.floors[floor].seats;const update=(fn:(items:Seat[])=>Seat[])=>setLayout({...layout,floors:{...layout.floors,[floor]:{...layout.floors[floor],seats:fn(seats)}}});
 const save=async()=>{const r=await fetch("/api/layout",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(layout)});setMessage(r.ok?"저장 완료":"저장 실패")};
 const add=(e:React.MouseEvent<HTMLDivElement>)=>{if(!edit||!candidate)return;const c=candidates.find(x=>(x.user_id||x.hostname||x.name)===candidate);if(!c)return;const rect=e.currentTarget.getBoundingClientRect();const id=`${floor}-SEAT-${String(seats.length+1).padStart(3,"0")}`;update(items=>[...items,{seat_id:id,x:Math.round((e.clientX-rect.left)/scale),y:Math.round((e.clientY-rect.top)/scale),w:90,h:30,name:c.name,user_id:c.user_id,hostname:c.hostname,ip:c.ip,dept:c.dept,email:c.email,color:"#fff566"}]);setSelected(id)};
 const move=(dx:number,dy:number)=>update(items=>items.map(s=>s.seat_id===selected?{...s,x:s.x+dx,y:s.y+dy}:s));const filtered=seats.filter(s=>!search||Object.values(s).join(" ").toLowerCase().includes(search.toLowerCase()));
 return <><header className="topbar"><div><p className="breadcrumb">Lab / Layout - User</p><h1>Layout - User</h1></div><span>{message}</span></header><section className="layout-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="이름 / User ID / IP / Hostname / 좌석ID 검색"/><select value={floor} onChange={e=>{setFloor(e.target.value);setSelected("")}}><option>18F</option><option>19F</option></select><label><input type="checkbox" checked={edit} onChange={e=>setEdit(e.target.checked)}/> 편집 모드</label>{edit&&<><select value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">추가할 사용자 선택</option>{candidates.map(c=><option key={c.user_id||c.hostname||c.name} value={c.user_id||c.hostname||c.name}>{c.name} · {c.user_id} · {c.hostname}</option>)}</select><button onClick={()=>move(-5,0)}>←</button><button onClick={()=>move(0,-5)}>↑</button><button onClick={()=>move(0,5)}>↓</button><button onClick={()=>move(5,0)}>→</button><button onClick={()=>update(x=>x.filter(s=>s.seat_id!==selected))}>삭제</button><button onClick={save}>저장</button></>}</section><section className="layout-body"><div ref={canvasRef} className="seat-canvas" onDoubleClick={add}><img ref={imageRef} src={`/api/layout/image/${floor}`} onLoad={()=>{const image=imageRef.current,canvas=canvasRef.current;if(image&&canvas)setScale(canvas.clientWidth/image.naturalWidth)}} />{filtered.map(seat=><button key={seat.seat_id} className={seat.seat_id===selected?"selected":""} style={{left:seat.x*scale,top:seat.y*scale,width:seat.w*scale,height:seat.h*scale,background:seat.color||"#fff566",fontSize:Math.max(7,10*scale)}} onClick={()=>setSelected(seat.seat_id)}>{seat.name||seat.seat_id}</button>)}</div><aside className="seat-info">{seats.find(s=>s.seat_id===selected)?Object.entries(seats.find(s=>s.seat_id===selected)!).map(([k,v])=><p key={k}><b>{k}</b><span>{String(v)}</span></p>):<p>좌석을 선택하세요. 편집 모드에서 사용자를 선택하고 배치도를 더블클릭하면 좌석이 추가됩니다.</p>}</aside></section></>}
