import {useEffect,useMemo,useState} from "react";
import ReactECharts from "echarts-for-react";
import type {EChartsOption} from "echarts";
import {MonthPicker} from "../components/MonthPicker";

type Job={id:string;status:string;message:string;sourceProcessed?:number;sourceTotal?:number;totalProcessed?:number;totalEvents?:number};
type Contribution={source:string;label:string;count:number|null;previousCount:number|null;delta:number|null;percent:number;mode:string};
type Trend={day:string|null;dayOfMonth:number;currentCount:number|null;previousDay:string|null;previousCount:number|null;monthDelta:number|null;monthChangePct:number|null;average:number|null;upper:number|null;lower:number|null;deviationPct:number|null;status:string};
type Anomaly=Trend&{contributions:Contribution[];findingMetrics:{newBehavior:number;frequency:number;spread:number};causes:string[];causeSummary:string};
type Comparison={source:string;label:string;previousTotal:number|null;previousDailyAverage:number|null;currentTotal:number|null;currentDailyAverage:number|null;dailyChange:number|null;changePct:number|null;status:string};
type Dashboard={selectedMonth:string;comparisonMonth:string;sourceLabel:string;kpi:{currentTotal:number;currentDailyAverage:number|null;previousTotal:number;previousDailyAverage:number|null;dailyAverageChange:number|null;dailyAverageChangePct:number|null;anomalyDays:number;peakCount:number;peakDay:string};months:{current?:string;previous?:string;currentDays?:number;previousDays?:number};trend:Trend[];anomalies:Anomaly[];topAnomalies:Anomaly[];sourceComparison:Comparison[]};
type Finding={finding_id:string;finding_type:string;summary:string;created_at:string;user_name?:string;hostname?:string;gate?:{reasons:string[]};behaviors?:Array<{type:string;value:string}>};
const sources=[['','전체'],['detections','Detection'],['xdr','Email XDR'],['inbound','Inbound'],['outbound','Outbound'],['dlp','DLP'],['firewall','Firewall']];
const initialMonth=new Date().toISOString().slice(0,7);
const empty:Dashboard={selectedMonth:initialMonth,comparisonMonth:'',sourceLabel:'전체',kpi:{currentTotal:0,currentDailyAverage:null,previousTotal:0,previousDailyAverage:null,dailyAverageChange:null,dailyAverageChangePct:null,anomalyDays:0,peakCount:0,peakDay:''},months:{},trend:[],anomalies:[],topAnomalies:[],sourceComparison:[]};
const number=(value:number|null|undefined,digits=0)=>value==null?'-':value.toLocaleString(undefined,{maximumFractionDigits:digits});
const signed=(value:number|null|undefined,suffix='%')=>value==null?'-':`${value>0?'+':''}${number(value,1)}${suffix}`;
const count=(value:number|null|undefined)=>value==null?'-':`${number(value)}건`;
const sourceColor=(source:string)=>({detections:'var(--trend-detection)',xdr:'var(--trend-xdr)',inbound:'var(--trend-email)',outbound:'var(--trend-outbound)',dlp:'var(--trend-file)',firewall:'var(--status-fail-bright)'})[source]||'var(--text-muted)';
function KpiSparkline({values,role,type="area",highlightPeak=false}:{values:Array<number|null>;role:string;type?:"area"|"line"|"bar";highlightPeak?:boolean}){const [color,setColor]=useState("");useEffect(()=>{const update=()=>setColor(getComputedStyle(document.documentElement).getPropertyValue(role).trim());update();window.addEventListener("smu-theme",update);return()=>window.removeEventListener("smu-theme",update)},[role]);const peakIndex=highlightPeak?values.reduce<number>((best,value,index)=>value!=null&&(best<0||value>(values[best]??-Infinity))?index:best,-1):-1;const option=useMemo<EChartsOption>(()=>{const common={data:values,animationDuration:450,animationEasing:"cubicOut" as const};if(type==="bar")return {animation:true,grid:{left:2,right:2,top:4,bottom:2},xAxis:{type:"category",show:false,data:values.map((_,index)=>index)},yAxis:{type:"value",show:false,min:0,scale:true},series:[{...common,type:"bar",barWidth:"54%",itemStyle:{color,borderRadius:[2,2,0,0]}}]};return {animation:true,grid:{left:2,right:2,top:6,bottom:2},xAxis:{type:"category",show:false,boundaryGap:false,data:values.map((_,index)=>index)},yAxis:{type:"value",show:false,scale:true},series:[{...common,type:"line",smooth:.42,showSymbol:false,connectNulls:false,lineStyle:{color,width:2.2},itemStyle:{color},areaStyle:type==="area"?{color:{type:"linear",x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color},{offset:1,color:"transparent"}]},opacity:.34}:undefined,markLine:type==="line"?{silent:true,symbol:"none",lineStyle:{color,opacity:.18,width:1},data:[{yAxis:0}]}:undefined,markPoint:peakIndex>=0?{silent:true,symbol:"circle",symbolSize:9,label:{show:false},itemStyle:{color,borderColor:color,borderWidth:1.5},data:[{coord:[peakIndex,values[peakIndex] as number]}]}:undefined}]};},[color,type,peakIndex,values]);if(!color)return null;return <ReactECharts className="learner-kpi-sparkline" option={option} notMerge lazyUpdate style={{height:64,width:"100%"}}/>}

function JobProgress({job,onCancel}:{job:Job;onCancel:()=>void}){const sourceTotal=job.sourceTotal||0,total=job.totalEvents||0;return <div className="global-job-progress scheduler-progress indexing learner-job-progress"><div><b>{job.message}</b><span>{number(job.sourceProcessed||0)} / {number(sourceTotal)}</span></div><div><b>전체 진행률</b><span>{number(job.totalProcessed||0)} / {number(total)}</span></div><button className="danger-action" onClick={onCancel}>분석 중단</button><i/></div>}
function TrendChart({rows,currentMonth,previousMonth,onSelect}:{rows:Trend[];currentMonth:string;previousMonth:string;onSelect:(day:number)=>void}){
  const [theme,setTheme]=useState<Record<string,string>>({});
  useEffect(()=>{const update=()=>{const css=getComputedStyle(document.documentElement),read=(name:string)=>css.getPropertyValue(name).trim();setTheme({current:read("--accent-main"),previous:read("--accent-secondary-soft"),average:read("--status-success-bright"),range:read("--trend-email"),danger:read("--status-fail-bright"),text:read("--text-secondary"),muted:read("--text-muted"),grid:read("--border-soft"),surface:read("--surface-raised")})};update();window.addEventListener("smu-theme",update);return()=>window.removeEventListener("smu-theme",update)},[]);
  const option=useMemo<EChartsOption>(()=>{
    const hasAverage=rows.some(row=>row.average!=null),hasRange=rows.some(row=>row.lower!=null&&row.upper!=null);
    const legend=[`${currentMonth} 당월`,`${previousMonth} 전월`,...(hasAverage?["평소 평균"]:[]),...(hasRange?["평소 범위"]:[]),"임계 초과"];
    const rangeSeries=hasRange?[{name:"range-base",type:"line" as const,stack:"normal-range",data:rows.map(row=>row.lower),showSymbol:false,connectNulls:false,lineStyle:{opacity:0},areaStyle:{opacity:0},silent:true,tooltip:{show:false}},{name:"평소 범위",type:"line" as const,stack:"normal-range",data:rows.map(row=>row.lower==null||row.upper==null?null:Math.max(0,row.upper-row.lower)),showSymbol:false,connectNulls:false,lineStyle:{opacity:0},areaStyle:{color:theme.range,opacity:.14},silent:true}]:[];
    const averageSeries=hasAverage?[{name:"평소 평균",type:"line" as const,data:rows.map(row=>row.average),smooth:.35,showSymbol:false,connectNulls:false,lineStyle:{color:theme.average,width:1.4,type:"dashed" as const,opacity:.7}}]:[];
    return {animationDuration:550,animationEasing:"cubicOut",color:[theme.current,theme.previous,theme.average,theme.range,theme.danger],grid:{left:56,right:24,top:58,bottom:38,containLabel:false},legend:{top:8,left:12,itemWidth:18,itemHeight:8,textStyle:{color:theme.text,fontSize:11},data:legend},tooltip:{trigger:"axis",backgroundColor:theme.surface,borderColor:theme.grid,textStyle:{color:theme.text},formatter:(params:any)=>{const index=params?.[0]?.dataIndex??0,row=rows[index];return `<b>${row?.day||`${row?.dayOfMonth}일`}</b><br/>당월&nbsp;&nbsp;${count(row?.currentCount)}<br/>전월&nbsp;&nbsp;${count(row?.previousCount)}<br/>평소 평균&nbsp;&nbsp;${count(row?.average)}<br/>정상 범위&nbsp;&nbsp;${count(row?.lower)} ~ ${count(row?.upper)}<br/>증감률&nbsp;&nbsp;${signed(row?.monthChangePct)}<br/>상태&nbsp;&nbsp;${row?.status==='HIGH'?'임계 초과':row?.status==='LOW'?'하한 미만':row?.currentCount==null?'데이터 없음':'정상'}`}},xAxis:{type:"category",boundaryGap:false,data:rows.map(row=>`${row.dayOfMonth}일`),axisLine:{lineStyle:{color:theme.grid}},axisTick:{show:false},axisLabel:{color:theme.muted,interval:4}},yAxis:{type:"value",min:0,axisLine:{show:false},axisTick:{show:false},axisLabel:{color:theme.muted,formatter:(value:number)=>number(value)},splitLine:{lineStyle:{color:theme.grid,type:"dashed",opacity:.5}}},series:[...rangeSeries,...averageSeries,{name:`${previousMonth} 전월`,type:"line",data:rows.map(row=>row.previousCount),smooth:.28,showSymbol:false,connectNulls:false,lineStyle:{color:theme.previous,width:1.8,opacity:.72}},{name:`${currentMonth} 당월`,type:"line",data:rows.map(row=>row.currentCount),smooth:.28,showSymbol:false,connectNulls:false,lineStyle:{color:theme.current,width:3},areaStyle:{color:theme.current,opacity:.05},z:4},{name:"임계 초과",type:"effectScatter",data:rows.map((row,index)=>row.status==='HIGH'&&row.currentCount!=null?[index,row.currentCount]:null).filter(Boolean),symbolSize:11,rippleEffect:{scale:2.4,brushType:"stroke"},itemStyle:{color:theme.danger,borderColor:theme.surface,borderWidth:2},z:8}]};
  },[rows,currentMonth,previousMonth,theme]);
  return <div className="chart-area learner-daily-chart"><ReactECharts option={option} notMerge lazyUpdate style={{height:330,width:"100%"}} onEvents={{click:(event:any)=>{const index=event?.dataIndex;if(typeof index==='number'&&rows[index]?.currentCount!=null)onSelect(rows[index].dayOfMonth)}}}/></div>
}
function Kpis({data}:{data:Dashboard}){const daily=data.trend.map(r=>r.currentCount),cards=[['total','당월 총 탐지',count(data.kpi.currentTotal),`관측 ${data.months.currentDays||0}일`,daily,'area',false],['average','당월 일평균',count(data.kpi.currentDailyAverage),`전월 ${count(data.kpi.previousDailyAverage)}`,daily,'area',false],['change','전월 대비 일평균',signed(data.kpi.dailyAverageChangePct),`일평균 ${signed(data.kpi.dailyAverageChange,'건')}`,data.trend.map(r=>r.monthChangePct),'line',false],['anomaly','임계 초과 일자',`${data.kpi.anomalyDays}일`,'HIGH 기준',data.trend.map(r=>r.currentCount==null||r.upper==null?null:Math.max(0,r.currentCount-r.upper)),'bar',false],['peak','당월 최고 탐지량',count(data.kpi.peakCount),data.kpi.peakDay?.slice(5)||'-',daily,'area',true]];return <section className="dash-top learner-kpis">{cards.map(([role,title,value,note,values,type,highlightPeak])=><article className={`dash-card asset-card learner-kpi ${role}`} key={title as string}><div className="learner-kpi-copy"><h2>{title as string}</h2><dl><div><dt>{note as string}</dt><dd>{value as string}</dd></div></dl></div><div className="learner-kpi-chart"><KpiSparkline values={values as Array<number|null>} role={role==="average"?"--accent-secondary-soft":role==="change"?"--status-warning-bright":role==="anomaly"?"--status-fail-bright":role==="peak"?"--status-success-bright":"--accent-main"} type={type as "area"|"line"|"bar"} highlightPeak={Boolean(highlightPeak)}/></div></article>)}</section>}
function AnomalyTable({rows,onSelect}:{rows:Anomaly[];onSelect:(r:Anomaly)=>void}){return <article className="dash-card top-analysis learner-anomaly-table"><h2>임계 초과 일자 TOP 5</h2><table><thead><tr><th>날짜</th><th>전월</th><th>당월</th><th>평균 대비</th><th>상태</th><th>주요 원인</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.day!} onClick={()=>onSelect(r)}><td>{r.day?.slice(5)}</td><td>{number(r.previousCount)}</td><td>{number(r.currentCount)}</td><td className="up">{signed(r.deviationPct)}</td><td><span className="status-pill failed">임계 초과</span></td><td>{r.causeSummary}</td></tr>):<tr><td colSpan={6}>임계치를 초과한 날짜가 없습니다.</td></tr>}</tbody></table></article>}
function SourceTable({rows,months}:{rows:Comparison[];months:Dashboard['months']}){const metric=(value:string)=><span className="metric-cell-content">{value}</span>;return <article className="dash-card top-analysis learner-source-table"><h2>소스별 월간 비교</h2><table><colgroup><col className="source-column"/>{Array.from({length:6},(_,index)=><col className="metric-column" key={index}/>) }<col className="status-column"/></colgroup><thead><tr><th rowSpan={2}>소스</th><th colSpan={2}>전월 ({months.previous})</th><th colSpan={2}>당월 ({months.current})</th><th colSpan={2}>전월 대비</th><th rowSpan={2}>상태</th></tr><tr><th>총 탐지</th><th>일평균</th><th>총 탐지</th><th>일평균</th><th>증감</th><th>증감률</th></tr></thead><tbody>{rows.map(r=><tr key={r.source}><td><span className="source-cell-content"><i className="source-indicator" style={{background:sourceColor(r.source)}}/>{r.label}</span></td><td>{metric(number(r.previousTotal))}</td><td>{metric(number(r.previousDailyAverage,1))}</td><td>{metric(number(r.currentTotal))}</td><td>{metric(number(r.currentDailyAverage,1))}</td><td>{metric(signed(r.dailyChange,'건'))}</td><td>{metric(signed(r.changePct))}</td><td><span className="status-cell-content"><span className={`source-status ${r.status.toLowerCase()}`}>{r.status==='UP'?'증가':r.status==='DOWN'?'감소':r.status==='SIMILAR'?'유사':'데이터 부족'}</span></span></td></tr>)}</tbody></table></article>}
function Detail({row,onOpen}:{row:Anomaly|null;onOpen:()=>void}){if(!row)return <article className="dash-card learner-anomaly-detail"><h2>이상 날짜 상세 분석</h2><p>임계 초과 날짜를 선택하세요.</p></article>;const positive=row.contributions.filter(x=>(x.delta||0)>0);return <article className="dash-card learner-anomaly-detail"><h2>{row.day} 비교 분석</h2><div className="learner-detail-content"><dl className="learner-detail-summary"><div><dt>전월 동일 일자</dt><dd>{count(row.previousCount)}</dd></div><div><dt>당월</dt><dd>{count(row.currentCount)}</dd></div><div><dt>증감</dt><dd>{row.monthDelta==null?'-':signed(row.monthDelta,'건')}</dd></div><div><dt>증감률</dt><dd>{signed(row.monthChangePct)}</dd></div><div><dt>평소 수준</dt><dd>{count(row.average)}</dd></div><div><dt>정상 범위</dt><dd>{count(row.lower)} ~ {count(row.upper)}</dd></div></dl><section className="learner-contribution-panel"><h3>{positive.length?'전월 대비 증가 기여':'소스별 기여도'}</h3>{row.contributions.filter(x=>positive.length?(x.delta||0)>0:(x.count||0)>0).map(x=><div className="learner-contribution" key={x.source}><span><i className="source-indicator" style={{background:sourceColor(x.source)}}/>{x.label}</span><i><b style={{width:`${Math.max(x.percent,1.5)}%`,background:sourceColor(x.source)}}/></i><strong>{positive.length?signed(x.delta,'건'):count(x.count)}</strong><em>{number(x.percent,1)}%</em></div>)}</section></div><footer><span>{row.causes.join(' · ')}</span><button className="refresh-button" onClick={onOpen}>원인 분석 열기</button></footer></article>}
function Drilldown({row,source,onClose}:{row:Anomaly;source:string;onClose:()=>void}){const [raw,setRaw]=useState(false),[items,setItems]=useState<Finding[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{const controller=new AbortController(),p=new URLSearchParams({start:row.day!,end:row.day!,source,view:'all',page:'1',pageSize:'30'});fetch(`/api/learner/findings?${p}`,{signal:controller.signal}).then(r=>r.json()).then(x=>setItems(x.data?.items||[])).finally(()=>setLoading(false));return()=>controller.abort()},[row.day,source]);const causes=[...row.contributions.filter(x=>(x.delta||0)>0).slice(0,3).map(x=>`${x.label} 활동이 전월 동일 일자보다 ${number(x.delta)}건 증가해 전체 증가의 ${number(x.percent,1)}%를 차지했습니다.`),row.findingMetrics.newBehavior?`신규 행동 ${number(row.findingMetrics.newBehavior)}건이 확인되었습니다.`:'',row.findingMetrics.frequency?`평소보다 반복 빈도가 높아진 행동 ${number(row.findingMetrics.frequency)}건이 확인되었습니다.`:''].filter(Boolean);const top=(values:string[])=>Object.entries(values.filter(Boolean).reduce<Record<string,number>>((a,v)=>(a[v]=(a[v]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,5);const users=top(items.map(i=>i.user_name||'')),devices=top(items.map(i=>i.hostname||'')),behaviors=top(items.flatMap(i=>(i.behaviors||[]).map(b=>b.value)));return <div className="modal-backdrop" onClick={onClose}><section className="detail-modal learner-drilldown" onClick={e=>e.stopPropagation()}><header><div><h2>{row.day} 원인 분석</h2><small>왜 이 날짜의 탐지량이 증가했나요?</small></div><button onClick={onClose}>×</button></header><div className="learner-cause-summary"><h3>주요 원인</h3><ol>{causes.map((c,i)=><li key={i}>{c}</li>)}</ol>{loading?<p>원인 근거 집계 중...</p>:<div className="learner-entity-summary">{[["주요 사용자",users],["주요 장비",devices],["주요 행동",behaviors]].filter(([,rows])=>(rows as [string,number][]).length).map(([title,rows])=><section key={title as string}><h4>{title as string}</h4>{(rows as [string,number][]).map(([name,total])=><p key={name}><span>{name}</span><b>{total}건</b></p>)}</section>)}</div>}</div><footer><button className="refresh-button" onClick={()=>setRaw(!raw)}>{raw?'원본 분석 결과 닫기':'원본 분석 결과 보기'}</button></footer>{raw&&(loading?<p>원본 분석 결과 조회 중...</p>:<table><thead><tr><th>유형</th><th>시간</th><th>요약</th><th>Gate 근거</th></tr></thead><tbody>{items.map(i=><tr key={i.finding_id}><td>{i.finding_type}</td><td>{i.created_at}</td><td>{i.summary}</td><td>{i.gate?.reasons?.join(' · ')}</td></tr>)}</tbody></table>)}</section></div>}
export function MachineLearningPage(){const [data,setData]=useState(empty),[month,setMonth]=useState(initialMonth),[source,setSource]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Anomaly|null>(null),[modal,setModal]=useState(false),[job,setJob]=useState<Job|null>(null);const busy=!!job&&['queued','running','cancelling'].includes(job.status);const load=()=>{setLoading(true);fetch(`/api/learner/dashboard?${new URLSearchParams({source,month})}`).then(r=>r.json()).then(x=>{setData(x.data);setSelected((x.data.topAnomalies||[])[0]||null)}).finally(()=>setLoading(false))};useEffect(load,[source]);useEffect(()=>{if(!busy||!job)return;const id=setInterval(()=>fetch(`/api/jobs/${job.id}`).then(r=>r.json()).then(x=>setJob(x.data)),1500);return()=>clearInterval(id)},[busy,job?.id]);const run=async(mode:string)=>{const start=`${month}-01`,end=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10),r=await fetch('/api/learner/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,sources:source?[source]:undefined,start,end})});setJob((await r.json()).data)};const controls=useMemo(()=><div className="dashboard-range filter-action-row learner-dashboard-controls"><label>월<MonthPicker value={month} onChange={setMonth}/></label><label>Source<select value={source} onChange={e=>setSource(e.target.value)}>{sources.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button onClick={load}>적용</button><button className="refresh-button" disabled={busy} onClick={()=>run('incremental')}>새 데이터 분석</button><button disabled={busy} onClick={()=>run('full')}>전체 다시 분석</button></div>,[month,source,busy]);return <><header className="topbar dash-topbar"><div><p className="breadcrumb">Lab / Machine Learning</p><h1>Machine Learning</h1><small>선택 월을 전월과 비교하고 평소 범위를 넘은 날짜를 확인합니다.</small></div>{controls}</header>{busy&&job&&<JobProgress job={job} onCancel={()=>fetch(`/api/jobs/${job.id}/cancel`,{method:'POST'})}/>}<Kpis data={data}/><section className="learner-dashboard-main"><article className="dash-card threat-card"><h2>전월 vs 당월 탐지량 ({data.sourceLabel})</h2>{loading?<p>월간 집계 불러오는 중...</p>:<TrendChart rows={data.trend} currentMonth={data.selectedMonth} previousMonth={data.comparisonMonth} onSelect={d=>setSelected(data.anomalies.find(x=>x.dayOfMonth===d)||null)}/>}</article><AnomalyTable rows={data.topAnomalies} onSelect={setSelected}/></section><section className="dash-bottom learner-dashboard-bottom"><SourceTable rows={data.sourceComparison} months={data.months}/><Detail row={selected} onOpen={()=>setModal(true)}/></section>{modal&&selected&&<Drilldown row={selected} source={source} onClose={()=>setModal(false)}/>}</>}
