import {memo,useCallback,useEffect,useMemo,useRef,useState} from "react";
import {DateRange} from "../components/DateRange";

type Finding={gate?:{visible:boolean;category:string;evidenceFamilies:string[];reasons:string[]};finding_id:string;source:string;finding_type:string;title:string;summary:string;user_name:string;department:string;hostname:string;created_at:string;reasons:string[];baseline:Record<string,unknown>;related_event_ids:string[];observed:Record<string,unknown>};
type LearnerJob={id:string;status:'queued'|'running'|'cancelling'|'completed'|'failed'|'cancelled';message:string;currentSource?:string;sourceProcessed?:number;sourceTotal?:number;totalProcessed?:number;totalEvents?:number;progressPercent?:number};
type Filters={source:string;type:string;start:string;end:string;view:string};
const sources:Array<[string,string]>=[['','전체'],['detections','Detection'],['xdr','Email XDR'],['inbound','Inbound'],['outbound','Outbound'],['dlp','DLP'],['firewall','Firewall']];
const types:Array<[string,string]>=[['','전체 유형'],['NEW_BEHAVIOR','새로운 행동'],['FREQUENCY_SPIKE','활동 증가'],['SIMILAR_GROUP','비슷한 이벤트']];
const PAGE_SIZE=30;
const sourceLabel=(key?:string)=>sources.find(x=>x[0]===key)?.[1]||key||'Learner';
const percent=(processed=0,total=0)=>total>0?processed/total*100:0;
const isAbortError=(error:unknown)=>error instanceof DOMException?error.name==='AbortError':error instanceof Error&&error.name==='AbortError';

const LearnerJobStatus=memo(function LearnerJobStatus({job,cancelling,onCancel}:{job:LearnerJob;cancelling:boolean;onCancel:()=>void}){
 const sourcePercent=percent(job.sourceProcessed,job.sourceTotal),totalPercent=percent(job.totalProcessed,job.totalEvents);
 return <div className="global-job-progress scheduler-progress indexing learner-job-progress">
  <div><b>{sourceLabel(job.currentSource)} 분석 중</b><span>{(job.sourceProcessed||0).toLocaleString()} / {(job.sourceTotal||0).toLocaleString()} ({sourcePercent.toFixed(1)}%)</span></div>
  <div><b>전체 진행률</b><span>{(job.totalProcessed||0).toLocaleString()} / {(job.totalEvents||0).toLocaleString()} ({totalPercent.toFixed(1)}%)</span></div><button className="danger-action" disabled={cancelling||job.status==='cancelling'} onClick={onCancel}>{cancelling||job.status==='cancelling'?'분석 중단 중...':'분석 중단'}</button><i/>
 </div>;
});

function LearnerToolbar({filters,onFiltersChange,onResultsReady}:{filters:Filters;onFiltersChange:(next:Filters)=>void;onResultsReady:()=>void}){
 const [status,setStatus]=useState('확인 중'),[job,setJob]=useState<LearnerJob|null>(null),[message,setMessage]=useState(''),[cancelling,setCancelling]=useState(false);
 const previousStatus=useRef<string|undefined>(undefined);
 useEffect(()=>{const controller=new AbortController();fetch('/api/system-info/process-status',{signal:controller.signal}).then(r=>r.json()).then(async payload=>{const learner=payload.data?.learner;setStatus(learner?.status||'unavailable');if(learner?.currentJobId){const response=await fetch(`/api/jobs/${learner.currentJobId}`,{signal:controller.signal}),body=await response.json();if(response.ok)setJob(body.data)}}).catch(error=>{if(error.name!=='AbortError')setStatus('unavailable')});return()=>controller.abort()},[]);
 useEffect(()=>{if(!job||!['queued','running','cancelling'].includes(job.status))return;const controller=new AbortController();const poll=async()=>{try{const response=await fetch(`/api/jobs/${job.id}`,{signal:controller.signal}),body=await response.json();if(response.ok)setJob(body.data)}catch(error){if(!isAbortError(error))setMessage('분석 상태를 확인하지 못했습니다.')}};const timer=window.setInterval(()=>void poll(),1500);return()=>{window.clearInterval(timer);controller.abort()}},[job?.id,job?.status]);
 useEffect(()=>{const current=job?.status;if(current&&['completed','cancelled'].includes(current)&&previousStatus.current!==current)onResultsReady();if(current&&!['queued','running','cancelling'].includes(current)){setCancelling(false);setMessage(current==='completed'?'분석이 완료되었습니다.':current==='cancelled'?'분석이 취소되었습니다.':job?.message||'분석 작업이 종료되었습니다.')}previousStatus.current=current},[job?.status,job?.message,onResultsReady]);
 const busy=!!job&&['queued','running','cancelling'].includes(job.status);
 const run=async(mode:string)=>{const response=await fetch('/api/learner/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,sources:filters.source?[filters.source]:undefined,start:filters.start,end:filters.end})}),payload=await response.json();if(response.ok){setJob(payload.data);setMessage(`분석 요청 · ${payload.data.id.slice(0,8)}`)}else setMessage(payload.message||payload.error?.message||'요청 실패')};
 const cancel=async()=>{if(!job)return;setCancelling(true);const response=await fetch(`/api/learner/jobs/${job.id}/cancel`,{method:'POST'}),payload=await response.json();if(response.ok){setJob(current=>current?{...current,status:'cancelling',message:'분석 중단 중...'}:current);setMessage('분석 중단 중...')}else{setMessage(payload.message||payload.error?.message||'중단 요청 실패');setCancelling(false)}};
 return <><header className="topbar"><div><p className="breadcrumb">Lab / Machine Learning</p><h1>Machine Learning</h1></div><span>Learner 상태 · {status}</span></header><section className="config-card"><div className="detection-tools"><div><h2>Learner Finding</h2><p>{message||"우리 환경의 행동 변화 중 확인할 결과를 조회합니다."}</p></div></div><div className="condition-list"><div className="source-filters">{[["review","확인 필요"],["all","전체 분석 결과"]].map(([key,label])=><label key={key}><input type="radio" name="learner-view" checked={filters.view===key} onChange={()=>onFiltersChange({...filters,view:key})}/><span>{label}</span></label>)}</div><div className="source-filters">{sources.map(([key,label])=><label key={key}><input type="radio" name="learner-source" checked={filters.source===key} onChange={()=>onFiltersChange({...filters,source:key})}/><span>{label}</span></label>)}</div><div className="filter-action-row"><label>유형<select value={filters.type} onChange={event=>onFiltersChange({...filters,type:event.target.value})}>{types.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><DateRange start={filters.start} end={filters.end} onStartChange={value=>onFiltersChange({...filters,start:value})} onEndChange={value=>onFiltersChange({...filters,end:value})}/><button className="primary-action" disabled={busy} onClick={()=>run('incremental')}>새 데이터 분석</button><button disabled={busy} onClick={()=>run('full')}>전체 다시 분석</button></div></div>{busy&&job&&<LearnerJobStatus job={job} cancelling={cancelling} onCancel={cancel}/>}</section></>;
}

const FindingCard=memo(function FindingCard({finding,onOpen}:{finding:Finding;onOpen:(finding:Finding)=>void}){return <article className="config-card learner-finding"><header><span>{types.find(item=>item[0]===finding.finding_type)?.[1]||finding.finding_type}</span><time>{finding.created_at}</time></header><h2>{finding.title}</h2><b>{[finding.user_name,finding.department,finding.hostname].filter(Boolean).join(' · ')||'매핑되지 않은 이벤트'}</b><p>{finding.summary}</p><h3>{finding.gate?.visible?"왜 확인해야 하나요?":"분석 결과로만 보관된 이유"}</h3><ul>{(finding.gate?.reasons?.length?finding.gate.reasons:finding.reasons).map((reason,index)=><li key={index}>{reason}</li>)}</ul><footer><span>관련 이벤트 {finding.related_event_ids.length.toLocaleString()}건</span><button onClick={()=>onOpen(finding)}>상세 / Raw / 과거 기준</button></footer></article>});

const FindingList=memo(function FindingList({filters,revision,onOpen}:{filters:Filters;revision:number;onOpen:(finding:Finding)=>void}){
 const [items,setItems]=useState<Finding[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{const controller=new AbortController(),query=new URLSearchParams({source:filters.source,findingType:filters.type,start:filters.start,end:filters.end,view:filters.view,page:String(page),pageSize:String(PAGE_SIZE)});setLoading(true);fetch(`/api/learner/findings?${query}`,{signal:controller.signal}).then(r=>r.json()).then(payload=>{setItems(payload.data?.items||[]);setTotal(payload.data?.pagination?.total||0)}).catch(error=>{if(!isAbortError(error)){setItems([]);setTotal(0)}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[filters.source,filters.type,filters.start,filters.end,filters.view,page,revision]);
 const totalPages=Math.max(1,Math.ceil(total/PAGE_SIZE));
 return <section><div className="learner-findings">{!loading&&items.length===0&&<div className="timeline-empty">저장된 분석 결과가 없습니다. Learner 분석을 실행하세요.</div>}{items.map(finding=><FindingCard finding={finding} onOpen={onOpen} key={finding.finding_id}/>)}</div><footer className="pagination"><span>총 {total.toLocaleString()}건 · 페이지당 {PAGE_SIZE}건</span><div><button disabled={loading||page<=1} onClick={()=>setPage(value=>value-1)}>이전</button><b>{page} / {totalPages}</b><button disabled={loading||page>=totalPages} onClick={()=>setPage(value=>value+1)}>다음</button></div></footer></section>;
});

export function MachineLearningPage(){const [filters,setFilters]=useState<Filters>({source:'',type:'',start:'',end:'',view:'review'}),[revision,setRevision]=useState(0),[selected,setSelected]=useState<Finding|null>(null);const resultsReady=useCallback(()=>setRevision(value=>value+1),[]),openFinding=useCallback((finding:Finding)=>setSelected(finding),[]),stableFilters=useMemo(()=>filters,[filters.source,filters.type,filters.start,filters.end,filters.view]);return <><LearnerToolbar filters={stableFilters} onFiltersChange={setFilters} onResultsReady={resultsReady}/><FindingList key={`${filters.source}:${filters.type}:${filters.start}:${filters.end}:${filters.view}`} filters={stableFilters} revision={revision} onOpen={openFinding}/>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail-modal" onClick={event=>event.stopPropagation()}><header><h2>{selected.title}</h2><button onClick={()=>setSelected(null)}>×</button></header><pre>{JSON.stringify({gate:selected.gate,observed:selected.observed,baseline:selected.baseline,reasons:selected.reasons,relatedEvents:selected.related_event_ids},null,2)}</pre></section></div>}</>}
