import { useEffect, useState } from "react";

type Item = { id: string; source: string; category: string; keywords: string[]; user: string; dept: string; time: string; name?: string; path?: string; site?: string; url?: string; event: string };

export function SensitivePage({ kind }: { kind: "files" | "sites" }) {
  const pageSize=100;
  const [category, setCategory] = useState("전체"); const [keyword, setKeyword] = useState(""); const [sources, setSources] = useState(kind === "files" ? ["DLP", "Outbound Mail"] : ["DLP"]); const [items, setItems] = useState<Item[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [total, setTotal] = useState(0); const [dataSource, setDataSource] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Item | null>(null); const [raw, setRaw] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const title = kind === "files" ? "Sensitive Files" : "Sensitive Sites";
  const load = async (nextPage = 1) => { setLoading(true); setError(""); try { const params = new URLSearchParams({ category, keyword, sources: sources.join(","), offset: String((nextPage-1)*pageSize), limit: String(pageSize) }); const response = await fetch(`/api/sensitive/${kind}?${params}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); setItems(payload.data.items); setCounts(payload.data.categoryCounts); setTotal(payload.data.total); setDataSource(payload.data.source); setPage(nextPage); setSelected(null); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => load(1), 250); return () => clearTimeout(timer); }, [category, keyword, sources.join(","),kind]);
  const toggle = (source: string) => setSources((current) => current.includes(source) ? current.filter((item) => item !== source) : [...current, source]);
  const showRaw = async (item: Item) => { try { const response = await fetch(`/api/sensitive/${kind}/${encodeURIComponent(item.id)}?sources=${encodeURIComponent(sources.join(","))}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); setRaw(payload.data.raw); } catch (reason) { setError(String(reason)); } };
  const categories = ["전체", ...Object.keys(counts)];
  const totalPages=Math.max(1,Math.ceil(total/pageSize));
  const pageNumbers=Array.from({length:Math.min(5,totalPages)},(_,index)=>Math.max(1,Math.min(totalPages-4,page-2))+index);
  return <><header className="topbar"><div><p className="breadcrumb">Forensics / {title}</p><h1>{title}</h1></div><div className="sensitive-actions">{kind === "files" && ["DLP", "Outbound Mail"].map((source) => <label key={source}><input type="checkbox" checked={sources.includes(source)} onChange={() => toggle(source)} />{source}</label>)}<input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder={kind === "files" ? "파일명 / 사용자 / 경로 검색" : "사이트 / 사용자 / URL 검색"} /></div></header>
    {error && <div className="error-banner">민감정보 조회 오류: {error}</div>}<section className="sensitive-layout"><aside className="category-list"><h3>분류</h3>{categories.map((name) => <button className={category === name ? "active" : ""} key={name} onClick={() => setCategory(name)}><span>{name}</span><b>{name === "전체" ? Object.values(counts).reduce((sum, value) => sum + value, 0) : counts[name]}</b></button>)}</aside>
      <section className="sensitive-table panel"><header><h2>{kind === "files" ? "민감 파일 후보" : "민감 사이트 후보"}</h2><span>{dataSource === "sqlite-index" ? "인덱스 검색 · " : "캐시 직접 검색 · "}{page.toLocaleString()} / {totalPages.toLocaleString()} 페이지 · 총 {total.toLocaleString()}건</span></header><div className="table-wrap"><table><thead><tr>{[kind === "files" ? "파일명" : "사이트", "분류", "탐지 키워드", "사용자", "부서", "시간"].map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{loading && items.length === 0 ? <tr><td colSpan={6} className="state-cell">민감정보 후보를 분류하는 중입니다...</td></tr> : items.length === 0 ? <tr><td colSpan={6} className="state-cell">분류된 후보가 없습니다.</td></tr> : items.map((item) => <tr className={selected?.id === item.id ? "selected-row" : ""} key={item.id} onClick={() => setSelected(item)}><td className="hostname">{kind === "files" ? item.name : item.site}</td><td>{item.category}</td><td>{item.keywords.join(", ")}</td><td>{item.user}</td><td>{item.dept}</td><td>{item.time}</td></tr>)}</tbody></table></div><footer className="sensitive-pagination"><span>페이지당 100개 · 현재 {items.length.toLocaleString()}개</span><div><button disabled={page===1||loading} onClick={()=>load(page-1)}>이전</button>{pageNumbers.map(number=><button key={number} className={number===page?"active":""} disabled={loading} onClick={()=>load(number)}>{number}</button>)}<button disabled={page===totalPages||loading} onClick={()=>load(page+1)}>다음</button></div></footer></section>
      <aside className="sensitive-detail">{selected ? <><h2>{kind === "files" ? selected.name : selected.site}</h2><dl><dt>출처</dt><dd>{selected.source}</dd><dt>분류</dt><dd>{selected.category}</dd><dt>탐지 키워드</dt><dd>{selected.keywords.join(", ")}</dd><dt>사용자 / 부서</dt><dd>{selected.user} / {selected.dept}</dd><dt>시간</dt><dd>{selected.time}</dd><dt>{kind === "files" ? "경로" : "URL/대상"}</dt><dd>{kind === "files" ? selected.path : selected.url}</dd><dt>이벤트</dt><dd>{selected.event}</dd></dl><button onClick={() => showRaw(selected)}>Raw 보기</button></> : <p>항목을 선택하면 상세 정보가 표시됩니다.</p>}</aside></section>
    {raw && <div className="modal-backdrop" onMouseDown={() => setRaw(null)}><section className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><header><h2>{title} Raw Detail</h2><button onClick={() => setRaw(null)}>×</button></header><pre>{JSON.stringify(raw, null, 2)}</pre></section></div>}
  </>;
}
