import { FormEvent, useState } from "react";

type Event = { time: string; source: string; user: string; userId: string; dept: string; asset: string; event: string; direction: string; peer: string; summary: string; indicator: string; raw: Record<string, unknown> };
type Group = { bucket: string; source: string; event: string; count: number; items: Event[] };
const sourceNames = ["Detection", "XDR", "Email", "Outbound Mail", "File"];

export function TimelinePage() {
  const [user, setUser] = useState(""); const [keyword, setKeyword] = useState(""); const [sources, setSources] = useState(sourceNames); const [groups, setGroups] = useState<Group[]>([]); const [selected, setSelected] = useState<Group | null>(null); const [raw, setRaw] = useState<Event | null>(null); const [totalEvents, setTotalEvents] = useState(0); const [totalGroups, setTotalGroups] = useState(0); const [dataSource, setDataSource] = useState(""); const [offset, setOffset] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const search = async (nextOffset = 0, append = false) => { setLoading(true); setError(""); try { const params = new URLSearchParams({ user, keyword, sources: sources.join(","), offset: String(nextOffset), limit: "250" }); const response = await fetch(`/api/timeline?${params}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); setGroups((current) => append ? [...current, ...payload.data.groups] : payload.data.groups); setTotalEvents(payload.data.pagination.totalEvents); setTotalGroups(payload.data.pagination.totalGroups); setDataSource(payload.data.source); setOffset(nextOffset + payload.data.groups.length); setSelected(null); } catch (reason) { setError(String(reason)); } finally { setLoading(false); } };
  const toggle = (source: string) => setSources((current) => current.includes(source) ? current.filter((item) => item !== source) : [...current, source]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!loading && sources.length && (user.trim() || keyword.trim())) search(); };
  const showRaw = (event: Event) => setRaw(event);
  return <><header className="topbar"><div><p className="breadcrumb">Forensics / Timeline</p><h1>Timeline</h1></div><div className="status-pill">전체 캐시 통합 검색</div></header>
    <form className="timeline-search" onSubmit={submit}><div><label>사용자</label><input value={user} onChange={(event) => setUser(event.target.value)} placeholder="사용자명 / User ID / 메일 / Hostname" /></div><div><label>키워드</label><input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="이벤트 / 제목 / 파일 / IP / 해시" /></div><button type="submit" disabled={loading || sources.length === 0 || (!user.trim() && !keyword.trim())}>{loading ? "전체 캐시 검색 중..." : "조회"}</button></form>
    <section className="source-filters">{sourceNames.map((source) => <label key={source}><input type="checkbox" checked={sources.includes(source)} onChange={() => toggle(source)} /><span>{source}</span></label>)}</section>
    {error && <div className="error-banner">Timeline 검색 오류: {error}</div>}
    <section className="timeline-summary"><span>이벤트 <b>{totalEvents.toLocaleString()}</b>건</span><span>그룹 <b>{totalGroups.toLocaleString()}</b>개</span>{dataSource && <span className={`index-source ${dataSource === "sqlite-index" ? "active" : "fallback"}`}>{dataSource === "sqlite-index" ? "인덱스 검색" : "캐시 직접 검색"}</span>}<small>날짜 선택과 무관하게 전체 캐시에서 검색합니다.</small></section>
    <section className="timeline-list">{groups.length === 0 && !loading && <div className="timeline-empty">사용자 또는 키워드를 입력해 전체 Detection/XDR/Inbound/Outbound/File 캐시를 검색하세요.</div>}{groups.map((group) => <article className={`timeline-group ${selected===group?"expanded":""}`} key={`${group.bucket}-${group.source}-${group.event}`}><button className={`timeline-card source-${group.source.replaceAll(" ", "-")} ${selected===group?"selected":""}`} onClick={() => setSelected(selected===group?null:group)} onContextMenu={(event) => {event.preventDefault();if(group.items[0])showRaw(group.items[0]);}}><time>{group.bucket}</time><div><span>{group.source}</span><h3>{group.event}</h3><p><b className="entity-name">{group.items[0]?.asset}</b> · {group.items[0]?.summary}</p></div><strong>{group.count.toLocaleString()}건</strong></button>{selected===group&&<div className="timeline-inline-detail"><header><b>하위 이벤트 {group.items.length.toLocaleString()}건</b><small>항목을 클릭하거나 우클릭하면 원본 RAW 데이터가 열립니다.</small></header>{group.items.map((item,index)=><button key={`${item.time}-${index}`} onClick={()=>showRaw(item)} onContextMenu={(event)=>{event.preventDefault();showRaw(item)}}><time>{item.time}</time><strong>{item.user} · {item.userId}</strong><span>{item.asset}</span><p>{item.direction}</p><small>{item.summary}</small><em>RAW 보기</em></button>)}</div>}</article>)}{offset < totalGroups && <button className="load-more" disabled={loading} onClick={() => search(offset, true)}>더 보기 ({Math.min(250, totalGroups - offset).toLocaleString()}개)</button>}</section>
    {raw&&<div className="modal-backdrop" onMouseDown={()=>setRaw(null)}><section className="detail-modal timeline-raw" onMouseDown={event=>event.stopPropagation()}><header><div><small>{raw.time} · {raw.source}</small><h2>{raw.event}</h2></div><button onClick={()=>setRaw(null)}>×</button></header><pre>{Object.keys(raw.raw||{}).length?JSON.stringify(raw.raw,null,2):"RAW 데이터를 찾지 못했습니다. Config에서 스마트 캐시 데이터 인덱싱을 다시 실행해 주세요."}</pre></section></div>}
  </>;
}
