import { useEffect, useState } from "react";

type Row = Record<string, string> & { id: string };
type Condition = { field: string; mode: "include" | "exclude"; query: string };
const configs = {
  outbound: { title: "Outbound Mail", defaultSort: "date", source: "cache/mailscreen", columns: [["date", "날짜"], ["mailProcess", "메일 처리"], ["sendResult", "전송 결과"], ["subject", "제목"], ["senderEmail", "발신자 (이메일)"], ["senderName", "발신자 명"], ["dept", "소속"], ["receiver", "수신자"], ["size", "크기"], ["policy", "적용 정책"], ["attachment", "첨부"]] },
  dlp: { title: "File / DLP", defaultSort: "time", source: "cache/dlp", columns: [["event", "이벤트"], ["time", "날짜/시간"], ["computer", "컴퓨터"], ["dept", "부서"], ["sourceIp", "소스 IP"], ["username", "사용자명"], ["source", "소스"], ["destination", "대상"], ["destinationType", "대상 유형"], ["destinationDetail", "목적지 세부정보"], ["fileSize", "파일 크기"], ["fileHash", "파일 해시"]] },
} as const;
const localDate = (offset = 0) => { const value = new Date(); value.setDate(value.getDate() + offset); return value.toISOString().slice(0, 10); };

export function TransferPage({ kind }: { kind: "outbound" | "dlp" }) {
  const config = configs[kind]; const fields = [["all", "ALL"], ...config.columns, ["rawData", "RawData"]];
  const [start, setStart] = useState(localDate(-6)); const [end, setEnd] = useState(localDate()); const [conditions, setConditions] = useState<Condition[]>([{ field: "all", mode: "include", query: "" }]);
  const [rows, setRows] = useState<Row[]>([]); const [total, setTotal] = useState(0); const [totalPages, setTotalPages] = useState(1); const [files, setFiles] = useState<string[]>([]); const [page, setPage] = useState(1); const [sort, setSort] = useState<string>(config.defaultSort); const [direction, setDirection] = useState<"asc" | "desc">("desc"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [detail, setDetail] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { setSort(config.defaultSort); setConditions([{ field: "all", mode: "include", query: "" }]); setPage(1); }, [kind, config.defaultSort]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); setError(""); const params = new URLSearchParams({ start, end, conditions: JSON.stringify(conditions.filter((item) => item.query.trim())), page: String(page), pageSize: "50", sort, direction }); fetch(`/api/transfers/${kind}?${params}`, { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); return payload; }).then((payload) => { setRows(payload.data.items); setTotal(payload.data.pagination.total); setTotalPages(payload.data.pagination.totalPages); setFiles(payload.data.source.files); }).catch((reason: unknown) => { if ((reason as Error).name !== "AbortError") setError(String(reason)); }).finally(() => setLoading(false)); }, 300); return () => { clearTimeout(timer); controller.abort(); }; }, [kind, start, end, conditions, page, sort, direction]);
  const update = (index: number, patch: Partial<Condition>) => { setConditions((current) => current.map((item, position) => position === index ? { ...item, ...patch } : item)); setPage(1); };
  const changeSort = (field: string) => { if (sort === field) setDirection(direction === "asc" ? "desc" : "asc"); else { setSort(field); setDirection("asc"); } setPage(1); };
  const openDetail = async (row: Row) => { try { const response = await fetch(`/api/transfers/${kind}/${row.id}?start=${start}&end=${end}`); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message || `HTTP ${response.status}`); setDetail(payload.data.raw); } catch (reason) { setError(String(reason)); } };
  return <><header className="topbar"><div><p className="breadcrumb">Detection / {config.title}</p><h1>{config.title}</h1></div><div className="date-range"><label>시작<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><span>~</span><label>종료<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label></div></header>
    <section className="summary-grid"><article><span>조회 결과</span><strong>{total.toLocaleString()}</strong><small>포함·제외 조건 적용 결과</small></article><article><span>조회 기간</span><strong className="range-value">{start}<b>~</b>{end}</strong><small>로컬 이벤트 시간 기준</small></article><article><span>캐시 파일</span><strong>{files.length}</strong><small>{config.source}</small></article></section>
    <section className="panel"><div className="detection-tools"><div><h2>AND 포함·제외 검색</h2><p>각 조건을 포함 또는 제외 방식으로 적용합니다.</p></div><button onClick={() => setConditions((current) => [...current, { field: "all", mode: "include", query: "" }])}>+ 조건 추가</button></div><div className="condition-list">{conditions.map((condition, index) => <div className="condition-row transfer-condition" key={index}><select value={condition.field} onChange={(event) => update(index, { field: event.target.value })}>{fields.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={condition.mode} onChange={(event) => update(index, { mode: event.target.value as Condition["mode"] })}><option value="include">포함</option><option value="exclude">제외</option></select><input value={condition.query} onChange={(event) => update(index, { query: event.target.value })} placeholder="검색어 입력..." />{conditions.length > 1 && <button onClick={() => setConditions((current) => current.filter((_, position) => position !== index))}>−</button>}</div>)}</div>
      {error && <div className="error-banner">조회 오류: {error}</div>}<div className="table-wrap detection-table"><table><thead><tr>{config.columns.map(([field, label]) => <th key={field}><button className="sort-button" onClick={() => changeSort(field)}>{label}<span>{sort === field ? direction === "asc" ? "↑" : "↓" : "↕"}</span></button></th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={config.columns.length} className="state-cell">데이터를 조회하는 중입니다...</td></tr> : rows.length === 0 ? <tr><td colSpan={config.columns.length} className="state-cell">조건에 일치하는 데이터가 없습니다.</td></tr> : rows.map((row) => <tr className={kind === "outbound" && row.sendResult.includes("실패") ? "failed-row" : ""} key={row.id} onDoubleClick={() => openDetail(row)}>{config.columns.map(([field]) => <td key={field} className={field === "computer" ? "entity-name" : field === "dept" ? "dept-name" : ""}>{row[field]}</td>)}</tr>)}</tbody></table></div><footer className="pagination"><span>총 {total.toLocaleString()}개 · 더블클릭: Raw Detail</span><div><button disabled={page <= 1} onClick={() => setPage(page - 1)}>이전</button><b>{page} / {totalPages}</b><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>다음</button></div></footer></section>
    {detail && <div className="modal-backdrop" onMouseDown={() => setDetail(null)}><section className="detail-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><span>{config.title} Raw Detail</span><h2>Transfer Event</h2></div><button onClick={() => setDetail(null)}>×</button></header><pre>{JSON.stringify(detail, null, 2)}</pre></section></div>}
  </>;
}
